### ISSUE TITLE
mx-12w

### ISSUE THREAD

**Issue by cod65** [ROBOTIS-GIT/DynamixelSDK#111]
Ive been trying to control dynamixels with python. 
I confirmed dynamixels are working with both dynamixel wizard and R+ manager. I am able to change position of motor and read/write control table. I am trying to do this with python now. I
i installed python 3.3.5.  windows 7, 64Bit
I run 'read_write.py'  protocol 1 and 2 and nothing much happens, short pause , then prompt appears. Python shell prints:

Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

>>> ================================ RESTART ================================
>>> 

Please fill out the questionaire to give you the best support service.  

- Which DYNAMIXEL is it?

  [MX 12w]  ( ex: MX-64AT , XM430-350R , PRO H54-100-S500-R , ...)

- Which CONTROLLER is it?

  [　usb2dynamixel　　] ( ex: OpenCM , OpenCR , Arduino Uno , PC via USB2Dynamixel , ... )

- Which VERSION of DynamixelSDK is it?

  ([NOTE] DynamixelSDK Q&A is not available anymore if it is older than ver. 3.0.0, but feedback us)

  [　3.4.7　　] ( ex: 3.4.2 , dxl_sdk_win32_v2_02.zip , ... )

- Any PICTURES or VIDEOS?

  ![](　Link the PICTURES or VIDEOS here, if necessary　)

- Any SOURCE SAMPLES?

  [](　Link the SOURCE SAMPLES here, if necessary　)

**Comment by cod65** [comment]
ok, well I realized my port wasnt set properly.

changed to:

DEVICENAME                  = "COM3".encode('utf-8')# Check which port is being used on your controller
                                                            # ex) Windows: "COM1"   Linux: "/dev/ttyUSB0"

now I get:


>>> ================================ RESTART ================================
>>> 
Succeeded to open the port!
Succeeded to change the baudrate!
Dynamixel has been successfully connected
Press any key to continue! (or press ESC to quit!)
Traceback (most recent call last):
  File "C:\Users\SPACE1970\Documents\DynamixelSDK-master\python\protocol1_0\read_writeHACK01.py", line 139, in <module>
    if getch() == chr(ESC_ASCII_VALUE):
  File "C:\Users\SPACE1970\Documents\DynamixelSDK-master\python\protocol1_0\read_writeHACK01.py", line 51, in getch
    return msvcrt.getch().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
>>>

**Comment by cod65** [comment]
commented out line 139:
    # if getch() == chr(ESC_ASCII_VALUE):
     #   break

and it started running!

but why?

**Comment by ROBOTIS-Leon** [comment]
@cod65 

Hi,

good work.

I have no idea since I've never seen this error before and doesn't become realized in my testing PC
but I've tracked some issue that must be related with your issue,
so let's start trying some other ways like replace ESC value to another.

**Comment by cod65** [comment]
I replaced to:

ESC_ASCII_VALUE             = 0x31


which presumably is the '1' key, if I understand correctly.

No difference, as  python cursor returns to '>>> '  before i enter a key, regardless.

**Comment by ROBOTIS-Leon** [comment]
@cod65 

Hi,

it seems like it doesn't match up with the value of the key, essentially.
Since I can't see the same error as you saw, and is perhaps not able to be shown in my computer though you send me your code, this time you should solve it (I will help you as much as I can). 

Dig more about python system, and let me know how you fixed it after all.

Sorry for that and thank you for your patience
