### ISSUE TITLE
No motors found on ROS

### ISSUE THREAD

**Issue by sejiny3** [ROBOTIS-GIT/DynamixelSDK#114]
Please help me!
[FATAL] [WallTime: 1504747042.179897] pan_tilt_port: No motors found.

Please fill out the questionaire to give you the best support service.  

- Which DYNAMIXEL is it?  [L54-50-S500-R]
- Which CONTROLLER is it?  [PC via USB2Dynamixel]
- Which VERSION of DynamixelSDK is it? [ROS(rosversion: 1.11.21) on Ubuntu 14.04]
- Any PICTURES or VIDEOS?
  1. I did: sudo apt-get install ros-indigo-dynamixel-motor
  2. I did as follows: http://wiki.ros.org/dynamixel_controllers/Tutorials/ConnectingToDynamixelBus
  3. picture of result: https://photos.app.goo.gl/Q5QgaQhYAlwpVmW32
  4. I already checked that this motor did well by just c++ on DynamixelSDK in the same computer as follow: https://photos.app.goo.gl/DiOfryUSiLc25Lpr2

**Comment by ROBOTIS-Leon** [comment]
@sejiny3 

Hi,

what you've tried in `iv.` is what we have released,
but `ii.` you've attached is neither our ros package nor is using DynamixelSDK 3.x.

So the thing I can tell you is that you should use DynamixelSDK lib by yourself or [Dynamixel-Workbench which; an official package for Dynamixel ROS application](https://github.com/ROBOTIS-GIT/dynamixel-workbench/) that uses DynamixelSDK lib, or we can't assist for the use of other oriented source. 

For the details of Dynamixel-Workbench, please comment the issue in the Dynamixel-Workbench issue bulletin.
