### ISSUE TITLE
Error in loadlibrary

### ISSUE THREAD

**Issue by marcohui95** [ROBOTIS-GIT/DynamixelSDK#125]
I am using dynamixel XH430-W210 and Window 10 laptop. When I run the matlab code in R2017a version, it always shows:

Error using loadlibrary
No supported compiler or SDK was found. You can install the freely available MinGW-w64 C/C++ compiler;
see Install MinGW-w64 Compiler. For more options, visit
http://www.mathworks.com/support/compilers/R2017a/.

Error in loadlibrary

Error in read_write (line 62)
    [notfound, warnings] = loadlibrary(lib_name, 'dynamixel_sdk.h', 'addheader', 'port_handler.h',
    'addheader', 'packet_handler.h');
 
I have already followed the software preparation on Youtube, setting up the solution of the output in the file with Visual Studio 2017 and set paths. Do anyone have ideas how to fix it?

**Comment by aeer92** [comment]
I have the same issue with my dynamixel MX-12W, same error message appears and I followed all the steps in the tutorials and videos. What does the error mean and how do we solve it?

**Comment by GrigoriyAY** [comment]
Hi, I had simular problem. Then I solved it by installing Microsoft Visual Studio Professional 2013. On some reason I couldn't use Microsoft Visual Studio 2015. May be it can help you.

**Comment by ROBOTIS-Leon** [comment]
@GrigoriyAY 

Thank you for your feedback

@marcohui95 @aeer92 

Hi,
sorry for the late reply

As @GrigoriyAY mentioned, some (but most) cases were solved by using DynamixelSDK library file that is  built in the other version of compilers.
Try some other <kbd>Platform toolset</kbd> option described [here](https://github.com/ROBOTIS-GIT/DynamixelSDK/wiki/3.2.2.1-CPP-Windows)

In the Matlab, there were so many issues in version compatibility with Microsoft Visual Studio everytime. 

I should find the exact reason of them anyway.

**Comment by ZHUIA** [comment]
did u manage to fix it @marcohui95 ..i am facing a similar problem

**Comment by ROBOTIS-Leon** [comment]
@ZHUIA 

Hi,

@GrigoriyAY said that he solved the problem by building new library file

I hope it helps you

**Comment by ZHUIA** [comment]
i tried using other [platform toolset] options like VS 2015 but still same problem..  error is shown in pic below
![image](https://user-images.githubusercontent.com/35397599/34935831-245f5452-fa1a-11e7-945e-707db41d147f.png)
any other suggestion please
