### ISSUE TITLE
132 	  Present Position 	 Current Position Value

### ISSUE THREAD

**Issue by elthef** [ROBOTIS-GIT/DynamixelSDK#128]
Please fill out the questionaire to give you the best support service.  

- Which DYNAMIXEL is it?
MX 106T
  [　-　]  ( ex: MX-64AT , XM430-350R , PRO H54-100-S500-R , ...)

- Which CONTROLLER is it?
USB2Dynamixel
  [　　　] ( ex: OpenCM , OpenCR , Arduino Uno , PC via USB2Dynamixel , ... )

- Which VERSION of DynamixelSDK is it?
Dynamixel protocol 2.0
  ([NOTE] DynamixelSDK Q&A is not available anymore if it is older than ver. 3.0.0, but feedback us)

  [　　　] ( ex: 3.4.2 , dxl_sdk_win32_v2_02.zip , ... )

I would like to find out if it is possible to reset the present position value without powering off and on the motor. 
Thank you and best regards
Edwin

**Comment by ROBOTIS-Leon** [comment]
@elthef 

Hi,
sorry for the late reply

I couldn't notice that what kind of use do you want by doing that. 
Since the encoder of the motor checks the position in every loop,
even if you change the present position value, it would be showing the real value again

Give me more hints to solve.

**Comment by ROBOTIS-Leon** [comment]
This issue will be closed since there was no actions for a while.
You can reopen this issue to show this issue to the users whenever.
