### ISSUE TITLE
Control Motors Though OpenCM Board Using The SDK

### ISSUE THREAD

**Issue by hthomas60** [ROBOTIS-GIT/DynamixelSDK#133]
I want to use the Dynimexel SDK to control motors that are connected to an OpenCM 9.04 and 384 board. So far I have not been able to get the motors to connect. I believe this is because the 9.04 board requires commands to be send over serial1 and the 384 board requires them to be send over serial3.

How do I send commands over serial1 and 3 using the C++ SDK code?

Thanks!

**Comment by ROBOTIS-Leon** [comment]
@hthomas60 

Hi, 
and sorry for the late. I hope that still you are working on this

You can get full source and examples of SDK c++ for OpenCM904 in 
[https://github.com/ROBOTIS-GIT/OpenCM9.04](https://github.com/ROBOTIS-GIT/OpenCM9.04)

but if you are currently using ArduinoIDE, you can get those sources without git clone by following the descriptions in:

[https://github.com/ROBOTIS-GIT/OpenCM9.04/wiki](https://github.com/ROBOTIS-GIT/OpenCM9.04/wiki)

Thanks and give me feedbacks

**Comment by ROBOTIS-Leon** [comment]
This issue will be closed since there was no actions for a while.
You can reopen this issue to show this issue to the users whenever.
