### ISSUE TITLE
Velocity Mode Safety Concerns

### ISSUE THREAD

**Issue by asoaresd** [ROBOTIS-GIT/DynamixelSDK#14]
Hi folks,
I would like to know if there is any possibility of shutting down the motor when it loses its communication, for example: I'm using usb2dynamixel and velocity mode on my motors, when I disconnect my usb2dynamixel from PC the motor keeps running, which is not good for what I'm using those motors.
Also I would like to ask if there's a shutting down in case my motor get stuck and increase the motor's current.

Thanks

**Comment by ROBOTIS-Leon** [comment]
Hey, how are you :)

Officially, the issues related with the thing except SDK have been supported by support@robotis.com, so next time I wish you use it. :D. I asked about that to the teammate related with that question, as you said, we don't have that kinda function in our actuators and there is no schedule for making it :(

Let's wait for another chance to get it! :)

I'm sorry for the inconvenience.
