### ISSUE TITLE
MX-28 controlled by arduino

### ISSUE THREAD

**Issue by chuchodel** [ROBOTIS-GIT/DynamixelSDK#140]
- Which DYNAMIXEL is it?
MX-28AT
- Which CONTROLLER is it?
Arduino Nano and Arduino Due
- Which VERSION of DynamixelSDK is it?
  DynamixelSDK 3.5.3  protocol 2.0

Hi 

I am trying to control a dynamixel MX28-AT with an Arduino nano board. I am using the protocol 2.0 and I tried to use the example code (link at the end) you have but it's not easy to understand. The code is based on C++ environment so there are many libraries that Arduino don't support. I couldn't compile the code because of this. If someone could share an example for Arduino, I really appreciate that.

https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/OpenCR/examples/07.%20DynamixelSDK/protocol2.0/read_write/read_write.ino

I followed the instructions on how to add the dynamixel sdk lib in the Arduino environment.

Jesus

**Comment by ROBOTIS-Leon** [comment]
@chuchodel 

Hi, 
and sorry for the late. I hope that still you are working this

we are currently developing the DynamixelSDK for Arduino (UNO level, especially), and will be released in 12.08.2017 or later. 

Thanks for patience, and please dont hesitate to ask more

**Comment by ROBOTIS-Leon** [comment]
This issue will be closed since there was no actions for a while.
You can reopen this issue to show this issue to the users whenever.
