### ISSUE TITLE
Truncated packet transmission on OSX

### ISSUE THREAD

**Issue by mcbridejc** [ROBOTIS-GIT/DynamixelSDK#142]
I'm using the USB2Dynamixel with OSX 10.10, to control a XM-430-W350T. 

Using latest master (3.5.3) of the SDK, I found that I had unreliable access to the servo. In perhaps 1 out of 10 calls to readXByteTxRx() it would fail with a timeout. 

Looking at the data line with an o-scope, I found that on failing transactions only the first one or two bytes of the TX packet were transmitted. After some debugging, I found that disabling the flushing of the tx buffer using `tcflush` immediately before the `write` call to send the packet fixed this issue. 

I don't know exactly what's going on. I hypothesize that somehow the write transaction, and the flush, after being sent by the USB device driver, can get performed out-of-order. In any case, is there a good reason for the flush before write? I could not see one, so I made a change and now I have reliable communication. If you also do not have a good reason for the flush, perhaps you should consider pulling this change in to your project. 

https://github.com/mcbridejc/DynamixelSDK/commit/74569ff0877012039bbce9fbd60c8ec61efee326

Cheers!

**Comment by ROBOTIS-Leon** [comment]
@mcbridejc 

hi,
absolutely. You've pointed out a great point!

Thank you and this will be in the source in the next release.
