### ISSUE TITLE
visual basic 2017 fails to build library

### ISSUE THREAD

**Issue by ZHUIA** [ROBOTIS-GIT/DynamixelSDK#155]
[3.5.4][MATLAB2017a][XM430-W350-R]
I am using the [XM430-W350-R] on windows 10 and [MATLAB 2017a].  I'm using `DynamixelSDK ver. 3.5.4` Following the  software preparation for  matlab using the youtube tutorial. need to download visual basic and build a library on it.. so i downloaded visual basic 2017 and when i  follow the tutorial the visual basic fails to  build the library showing many errors like 
Error	C1083	Cannot open include file: 'group_sync_read.h': No such file or directory	
What should i do to fix this

**Comment by ROBOTIS-Leon** [comment]
@ZHUIA 

Hi,

`visual basic 2017` ?, no it's visual studio 2017, and it compiles c language SDK files.
of course it can't include the `group_sync_read.h` file, and it doesn't know what it is

See the wiki [here](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/c_windows/#c-windows)to know how to build all things

**Comment by ZHUIA** [comment]
yeah sorry VS not Vb.. fixed the issue
