### ISSUE TITLE
General question regarding the startup procedure and calibration of MX-series

### ISSUE THREAD

**Issue by alborzs** [ROBOTIS-GIT/DynamixelSDK#156]
I don't know how to tackle this problem. This is not an issue, more a general question and I hope that this is the right place to ask it.

We have a couple of **MX-106** and **MX-64** connected in a network (in extended position control mode). When we first power up the servos, the absolute first time that we request a Goal Position, the servos might rotate one whole revolution before they stop at the requested position. I suppose that this behavior has something to do with the fact they have booted up and they do not know their position.

This is really unwanted, in our system we make sure to go to a known position before we turn off everything, still when the servos are restarted they might do a 360 before they stop at the right position. How can be change this behaviors?

**Comment by ROBOTIS-Leon** [comment]
@alborzs 

Hi,

and this is the idea from ROBOTIS HQ: Yes, it can't remember where it was going after shutdown and reboot, so you should make the controller remember before it happens.

It would be a great help if someone has different ideas

**Comment by ROBOTIS-Leon** [comment]
@alborzs

Hi,

to make the issue be solved, I will send this to [robotis forum](http://en.robotis.com/service/forum_view.php?slg=&page_type=&bbs_no=2406752).
you can follow up the status of how your issue is being solved.
