### ISSUE TITLE
[3.5.4][Python][MX-28AT] Unable to load DLL using Ctypes

### ISSUE THREAD

**Issue by arvindsa** [ROBOTIS-GIT/DynamixelSDK#172]
- SDK - DynamixelSDK ver. 3.5.4`
-Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
-Hardware: using FTR232 USBto Serial with a Buffer. I am able to control the MX28AT using Dynzmixel Wizard
- When running SDK example DynamixelSDK-3.5.4\python\protocol1_0\ping.py , the following error occurs

Traceback (most recent call last):
  File "C:\Users\Arvind\Downloads\DynamixelSDK-3.5.4\python\dynamixel_functions_py\dynamixel_functions.py", line 24, in <module>
    dxl_lib = cdll.LoadLibrary("../../c/build/win32/output/dxl_x86_c.dll")  # for windows 32bit
  File "C:\Python27\lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

As per http://support.robotis.com/en/software/dynamixel_sdk/usb2dynamixel/usb2dxl_windows.htm, I have installed Microsoft Visual C++ 2005 re-distribution. I have tried versions from 3.4.1 and all gives the same error. I have tried on two different computer. Same results.

**Comment by ROBOTIS-Leon** [comment]
@arvindsa 

Hi,

the manual you've linked is very old. Please look at [New DynamixelSDK Manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/overview/)

and try again.

If you have any further question, don't hesitate but ask.

**Comment by ROBOTIS-Leon** [comment]
This issue will be closed since there was no actions for a while.
You can reopen this issue to show this issue to the users whenever.
