### ISSUE TITLE
[3.5.4][C++][USB2Dynamixel][XM430-W210-T] Issue: Torque-Current Question

### ISSUE THREAD

**Issue by AminMohammadi** [ROBOTIS-GIT/DynamixelSDK#173]
I have two XM430-W210-T dynamixels, and I want to control torque of the motor. I have torque-current graph. 

![torque_current](https://user-images.githubusercontent.com/29506541/37558904-ac3626b8-29e9-11e8-8553-46213155e976.png)

1. I looked at emanual and it says that current limit is 1193(address is bellow).

http://emanual.robotis.com/docs/en/dxl/x/xm430-w210/#current-limit

Does it mean that maximum goal current value is 1193? I tested 2000, but it didn't give me error. What is the maximum current value I can give to the motor? I saw bellow page(under basic features) and it says that current based torque control has 4096 steps and each step is 2.96 mA. 

http://www.robotis.us/dynamixel-xm430-w210-t/

But emanual says 1193 is current limit. When I connect motor to R+ Manager 2.0 I see 1193 as current limit. I'm confused what is the maximum and minimum current limits?

2. How much current is one step of torque control? Is it 2.96 mA?

3. I have two Dynamixels(same model), and I want them to be exactly the same in rotation, velocity, acceleration, and everything. I checked R+ Manager 2.0, and it seems that every parameter is the same for both motors, but when I check the data on terminal(printf) I see that one motor is slightly faster than the other. How to fix this problem?

4. What is motor calibration and how to do it?

5. Each iteration takes 16ms. How can I increase it? One user recommended decreasing latency settings, but I don't know how to do it. I set baud rate to 2Mbps, but still 16ms.

Thanks

**Comment by ROBOTIS-Leon** [comment]
@AminMohammadi 

Hi,

since here can't handle the issue you've commented, I will send this to [robotis forum](http://en.robotis.com/service/forum_view.php?slg=&page_type=&bbs_no=2406732).
you can follow up the status of how your issue is being solved.
