### ISSUE TITLE
Dynamixel Monitor

### ISSUE THREAD

**Issue by 2Guz** [ROBOTIS-GIT/DynamixelSDK#18]
Hi again,
I'm currently trying to reset the dynamixel using the dynamixel monitor because I am running linux and there is not roboplus for linux yet. However, i tried inputting commands that did not work. I was wondering if there is a way to fix it. I have attached a picture of what I typed and the error.

Thank you!

![screenshot from 2016-07-18 17 08 21](https://cloud.githubusercontent.com/assets/20097358/16930540/b4600894-4d0a-11e6-9cfd-6152e4849bfa.png)

**Comment by ROBOTIS-Leon** [comment]
Hey, how are you

Try input 
`reset1 2` to reset dynamixel#2

Ping works if input `ping 2`

Thank you
