### ISSUE TITLE
Dynamixel Monitor

### ISSUE THREAD

**Issue by 2Guz** [ROBOTIS-GIT/DynamixelSDK#19]
Hi,
I'm currently trying to reset the dynamixel using the dynamixel monitor because I am running linux and there is no roboplus for linux yet. I tried inputting commands that did not work. I was wondering if there is a way to fix it. I have attached a picture of what I typed and the error. I was trying to see if the commands worked, and I am trying to factory reset the dynamixel.

Things I would like to do:
1. Change ID of Dynamixel
2. Factory Reset the Dynamixel

Thank you!

![screenshot from 2016-07-18 17 08 21](https://cloud.githubusercontent.com/assets/20097358/16930540/b4600894-4d0a-11e6-9cfd-6152e4849bfa.png)

**Comment by ROBOTIS-Leon** [comment]
Factory Reset makes your Dynamixel be reset as ID:1, Baudrate:57600

Either `reset1 2` or `rst1 2` is OK if you want to factory reset ID2 Dynamixel which uses protocol 1.0

Thank you!
