### ISSUE TITLE
[3.5.4][C++][USB2Dynamixel2][H54-100-S500-R] Issue : GroupBulkRead addparam error

### ISSUE THREAD

**Issue by tr-gis** [ROBOTIS-GIT/DynamixelSDK#196]
- I'm using `DynamixelSDK ver. 3.5.4`

- I'm using `C++/example/protocol2.0/bulk_read_write` 

 - I'm using `USB2Dynamixel2` serial converter

- I'm using `H54-100-S500-R and H54-200-S500-R`

- and I'm having an `issue`:

Cannot add multiple parameters for read operation using GroupBulkRead::addParam() function.

 I have two dynamixel Pro Motors connected via daisy chain. I would like to read and write velocity, position values to them. Using the bulk_read_write.cpp example under protocol two, I have managed to read and write **position** values from the two motors.

The next was to expand this to velocity values too. However when I tried adding parameters for reading velocity values I get the following error message : 

`grouBulkRead addparam failed`

Looking into the code for GroupBulkRead::addParam function

```
bool GroupBulkRead::addParam(uint8_t id, uint16_t start_address, uint16_t data_length)
{
  if (std::find(id_list_.begin(), id_list_.end(), id) != id_list_.end())   // id already exist
    return false;

  id_list_.push_back(id);
  length_list_[id]    = data_length;
  address_list_[id]   = start_address;
  data_list_[id]      = new uint8_t[data_length];

  is_param_changed_   = true;
  return true;
}
```

It looks like we cannot add multiple read parameters for the same ID. Can you  please confirm if this is the case ?. If so, is there any other method for adding multiple parameters for the same ID ?.

I can think of a workaround by writing two code, one for position and velocity but that seems like a overkill. 

Thanks

**Comment by routiful** [comment]
Hi :)

Unfortunately, you can't multiple read parameters for the same ID to use bulkRead. It supports read different parameters under different ID. 
If you want to read simultaneously multiple read parameters for the same ID, you can use [readRX()](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/api_reference/cpp/cpp_packethandler/#readrx) function with indirect address.

I attached a reference link

http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/cpp_indirect_address_protocol_2_0/#cpp-indirect-address-protocol-20

Thanks

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
