### ISSUE TITLE
[3.6.0][C][USB2Dynamixel][MX-64] Issue : [TxRxResult] Incorrect status packet!

### ISSUE THREAD

**Issue by serogamon** [ROBOTIS-GIT/DynamixelSDK#206]
First of all:
I'm using `DynamixelSDK ver. 3.6.0`
I'm using `C` Language
 I'm using `USB2Dynamixel` serial converter
I'm using `MX-64`

Hello, i follow the steps from the tutorial video and my programm write this when i click on run:

`Succeeded` to open the port!
Succeeded to change the baudrate!
Dynamixel has been successfully connected 
Dynamixel has been successfully connected 
Press any key to continue! (or input e to quit!)

[ID:001] Present Position : 1806 	 [ID:002] Is Moving : 0
Press any key to continue! (or input e to quit!)

[ID:001] Present Position : 1809 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 1817 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 1824 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 1831 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 1838 	 [ID:002] Is Moving : 0
[TxRxResult] Incorrect status packet!
[ID:001] groupBulkRead getdata failed>> `

When i erase the code for getdata then my servos works correctly but every few steps it writes "incorrect status packet" and the present position is "0" but after that the servos go on:

`Succeeded` to open the port!
Succeeded to change the baudrate!
Dynamixel has been successfully connected 
Dynamixel has been successfully connected 
Press any key to continue! (or input e to quit!)

[TxRxResult] Incorrect status packet!
[ID:001] Present Position : 2291 	 [ID:002] Is Moving : 0
[TxRxResult] Incorrect status packet!
[ID:001] Present Position : 0 	 [ID:002] Is Moving : 0
[TxRxResult] Incorrect status packet!
[ID:001] Present Position : 0 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2271 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2267 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2262 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2259 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2254 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2250 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2245 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2241 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2236 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2231 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2227 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2222 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2217 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2212 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2207 	 [ID:002] Is Moving : 0
[TxRxResult] Incorrect status packet!
[ID:001] Present Position : 0 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2189 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2182 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2177 	 [ID:002] Is Moving : 0
[TxRxResult] Incorrect status packet!
[ID:001] Present Position : 0 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2166 	 [ID:002] Is Moving : 0
[TxRxResult] Incorrect status packet!
[ID:001] Present Position : 0 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2156 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2151 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2146 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2141 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2136 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2130 	 [ID:002] Is Moving : 0
[ID:001] Present Position : 2125 	 [ID:002] Is Moving : 0`

I have absolutly no idea what this mean

**Comment by robotpilot** [comment]
Hi, @serogamon,
I am sorry for the inconvenience.
I need more details kinda environments like hardware settings, software source code (the original example filename you used). the number of motors in use. And similar problems can be caused by user's development environment and motor setting settings. There were similar issues in the following link. Have you checked?
https://github.com/ROBOTIS-GIT/DynamixelSDK/search?q=TxRxResult%5D+Incorrect+status+packet&type=Issues

**Comment by serogamon** [comment]
Hi, i will reset the motor settings tomorrow. I keep you updated.

Thank you for the answer.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
