### ISSUE TITLE
[3.5.4][MATLAB][USB2Dynamixel2][MX-64] Issue : Can't read present position data while in velocity operating mode using matlab.

### ISSUE THREAD

**Issue by kinter107** [ROBOTIS-GIT/DynamixelSDK#207]
Hi,  i'm using dynamixel mx-64 servo and commanding it using matlab with no problem , but i cannot read it's position while in velocity operating mode and i get the error below :
**[TxRxResult] Protocol does not support This function!**

here is my code :
`clc;
clear all;

lib_name = '';

if strcmp(computer, 'PCWIN')
  lib_name = 'dxl_x86_c';
elseif strcmp(computer, 'PCWIN64')
  lib_name = 'dxl_x64_c';
elseif strcmp(computer, 'GLNX86')
  lib_name = 'libdxl_x86_c';
elseif strcmp(computer, 'GLNXA64')
  lib_name = 'libdxl_x64_c';
elseif strcmp(computer, 'MACI64')
  lib_name = 'libdxl_mac_c';
end

% Load Libraries
if ~libisloaded(lib_name)
    [notfound, warnings] = loadlibrary(lib_name, 'dynamixel_sdk.h', 'addheader', 'port_handler.h', 'addheader', 'packet_handler.h', 'addheader', 'group_sync_write.h', 'addheader', 'group_sync_read.h');
end

% Control table address
ADDR_PRO_TORQUE_ENABLE          = 64;                 % Control table address is different in Dynamixel model
ADDR_PRO_OPERATING_MODE          = 11;
ADDR_PRO_GOAL_POSITION          = 116;
ADDR_PRO_GOAL_VELOCITY          = 104;
ADDR_PRO_PRESENT_POSITION       = 132;
ADDR_PRO_PRESENT_VELOCITY       = 128;
% Data Byte Length1
LEN_PRO_GOAL_POSITION       = 4;
LEN_PRO_PRESENT_POSITION    = 4;
LEN_PRO_GOAL_VELOCITY       = 4;
LEN_PRO_PRESENT_VELOCITY    = 4;
% Protocol version
PROTOCOL_VERSION            = 2.0;          % See which protocol version is used in the Dynamixel

% Default setting
DXL1_ID                     = 1;            % Dynamixel#1 ID: 1
DXL2_ID                     = 2;            % Dynamixel#2 ID: 2
BAUDRATE                    = 57142;
DEVICENAME                  = 'COM3';       % Check which port is being used on your controller
                                            % ex) Windows: 'COM1'   Linux: '/dev/ttyUSB0' Mac: '/dev/tty.usbserial-*'
                                            
TORQUE_ENABLE               = 1;            % Value for enabling the torque
TORQUE_DISABLE              = 0;            % Value for disabling the torque
DXL_MINIMUM_POSITION_VALUE  = 0;      % Dynamixel will rotate between this value
DXL_MAXIMUM_POSITION_VALUE  = 4095;       % and this value (note that the Dynamixel would not move when the position value is out of movable range. Check e-manual about the range of the Dynamixel you use.)
DXL_MINIMUM_VELOCITY_VALUE  = 0;
DXL_MAXIMUM_VELOCITY_VALUE  = 435;
DXL_MOVING_STATUS_THRESHOLD = 10;           % Dynamixel moving status threshold

ESC_CHARACTER               = 'e';          % Key for escaping loop

COMM_SUCCESS                = 0;            % Communication Success result value
COMM_TX_FAIL                = -1001;        % Communication Tx Failed

% Initialize PortHandler Structs
% Set the port path
% Get methods and members of PortHandlerLinux or PortHandlerWindows
port_num = portHandler(DEVICENAME);
% Initialize PacketHandler Structs
packetHandler();

% Initialize Groupsyncwrite Structs
groupwrite_num = groupSyncWrite(port_num, PROTOCOL_VERSION, ADDR_PRO_GOAL_VELOCITY, LEN_PRO_GOAL_VELOCITY);

% Initialize Groupsyncread Structs for Present Position
groupread_num = groupSyncRead(port_num, PROTOCOL_VERSION, ADDR_PRO_PRESENT_VELOCITY, LEN_PRO_PRESENT_VELOCITY);
groupread_num_p = groupSyncRead(port_num, PROTOCOL_VERSION, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
index = 2;
dxl_comm_result = COMM_TX_FAIL;           % Communication result
dxl_addparam_result = false;              % AddParam result
dxl_getdata_result = false;               % GetParam result
dxl_goal_velocity = [DXL_MINIMUM_VELOCITY_VALUE 0];         % Goal position

dxl_error = 0;                              % Dynamixel error
dxl1_present_velocity = 0;                  % Present position
%dxl2_present_velocity = 0;
% Open port
if (openPort(port_num))
    fprintf('Succeeded to open the port!\n');
else
    unloadlibrary(lib_name);
    fprintf('Failed to open the port!\n');
    input('Press any key to terminate...\n');
    return;
end
% Set port baudrate
if (setBaudRate(port_num, BAUDRATE))
    fprintf('Succeeded to change the baudrate!\n');
else
    unloadlibrary(lib_name);
    fprintf('Failed to change the baudrate!\n');
    input('Press any key to terminate...\n');
    return;
end
% Enable Dynamixel#1 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL1_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL1_ID);
end
% Add parameter storage for Dynamixel#1 present velocity value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL1_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL1_ID);
  return;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Add Dynamixel#1 goal velocity value to the Syncwrite storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL1_ID, typecast(int32(dxl_goal_velocity(index)), 'uint32'), LEN_PRO_GOAL_VELOCITY);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL1_ID);
        return;
    end
    % Syncwrite goal velocity
    groupSyncWriteTxPacket(groupwrite_num);
    dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
    if dxl_comm_result ~= COMM_SUCCESS
        fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
    end
     % Clear syncwrite parameter storage
    groupSyncWriteClearParam(groupwrite_num)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   while 1
    % Syncread present position % Velocity
        %POSITION
%         groupSyncReadTxRxPacket(groupread_num_p);
%         dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
%         if dxl_comm_result ~= COMM_SUCCESS
%             fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
%         end
% 
%         % Check if groupsyncread data of Dynamixel#1 is available
%         dxl_getdata_result = groupSyncReadIsAvailable(groupread_num_p, DXL1_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
%         if dxl_getdata_result ~= true
%           fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
%           return;
%         end
        % VELOCITY
        groupSyncReadTxRxPacket(groupread_num);
        dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
        if dxl_comm_result ~= COMM_SUCCESS
            fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
        end

        % Check if groupsyncread data of Dynamixel#1 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL1_ID, ADDR_PRO_PRESENT_VELOCITY, LEN_PRO_PRESENT_VELOCITY);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end
          % Get Dynamixel#1 present position value
        dxl1_present_position = groupSyncReadGetData(groupread_num_p, DXL1_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        % Get Dynamixel#1 present velocity value
        dxl1_present_velocity = groupSyncReadGetData(groupread_num, DXL1_ID, ADDR_PRO_PRESENT_VELOCITY, LEN_PRO_PRESENT_VELOCITY);
        [dxl1_present_velocity dxl1_present_position] 
   end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    
% Close port
closePort(port_num);

% Unload Library
unloadlibrary(lib_name);

close all;
clear all;
`

**Comment by robotpilot** [comment]
Hi @kinter107,

Thank you for sharing all the progress and its references.
When I tested it briefly, there was no problem getting the current position in velocity mode. 
Have you finished testing a single motor?

**Comment by kinter107** [comment]
Hi @robotpilot,

Thanks for your feedback.
actually i'm working with 2 motors and my purpose is to control a 2 degree of freedom parallel robot Named TezGoz and you can Google it if you don't know it .
But for testing my code before implementing on the bot, i use one motor and there was no success sadly , I think the problem might be related to my code . 
Can you use My code And test it if you have access to any dynamixels ?!

**Comment by robotpilot** [comment]
Hi @kinter107,
I modified it based on your code and tested it. With two motors in velocity mode.
I was able to get the value without any problem when I read the position value while rotating at the speed. You should refer to the code in the link below and try again.
https://gist.github.com/robotpilot/9bc2ba473ec8111c474ccbe209a500bb

**Comment by kinter107** [comment]
Thanks alot @robotpilot
Tomorrow, i will go to university and test The code.
i will share the results with You here.

**Comment by kinter107** [comment]
Hi again @robotpilot 
today i tested your code with 2 servos and it successfully worked, so checked it with mine and finally found out where was the problem !!
i should have put the following code between lines 115-116 :
`
% Add parameter storage for Dynamixel#1 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_p, DXL1_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL1_ID);
  return;
end
`
Thanks alot man you helped me so far ...
i really appreciate for the time you spend to solve my problem.

**Comment by robotpilot** [comment]
It is good to hear back from you!!!
Please, let me know if you have any questions on this issues.
Thanks. :)
