### ISSUE TITLE
Interfacing DynamixelSDK with Rasberrypi 3 using Half Duplex Converter Circuitry

### ISSUE THREAD

**Issue by ozzdemir** [ROBOTIS-GIT/DynamixelSDK#208]
Hello, I am using XL-XL430-W250 and I want to interface with it over Rasberry Pi3. I was planning to do it by using a little circuitry as recommended in e-manuel to convert full duplex UART to half duplex one. To do that, I was writing a python script inspired from https://github.com/jes1510/python_dynamixels . While doing it, I found out about dynamixel sdk and I was curious about whether or not I can change the sdk to interface over the circuitry since it requires an external direction pin. Thanks in advance.
![xl_series_circuit](https://user-images.githubusercontent.com/30624975/42509641-e0966676-844c-11e8-8676-4ad125ead9f4.png)

**Comment by robotpilot** [comment]
Hi @ozzdemir 

In general embedded board, I/O direction of a port is changed when Tx and Rx are switched. For SBCs and PCs, however, we recommend using U2D2(USB2Dynamixel2) officially rather than controlling them. Also, Raspberry Pi's UART is highly unstable in transmission speed, so high-speed communication is impossible and we recommend not to use it. You can find the information of U2D2 from the link below. I recommend you use this with SBC like Raspberry Pi.
http://emanual.robotis.com/docs/en/parts/interface/u2d2/

**Comment by ozzdemir** [comment]
Thanks for your recommendations @robotpilot , I've already read about U2D2 and other devices but the thing I was curious was is there a way to modify sdk so that it changes IO port automatically as in jes1510's script with modifying just a little part instead of whole sdk functions.

**Comment by robotpilot** [comment]
I don't recommend using Raspberry Pi's UART to communicate with Dynamixels. But to answer your question, you can find the function of txPacket or rxPacket (for example) and change the value of the direction pin to the function that sends and receives the packet. For example, see the link code below for how to change each port on an embedded board called OpenCR.

https://github.com/ROBOTIS-GIT/OpenCR/blob/28979242c9553cf46e819c575c57fb6db345dd5e/arduino/opencr_arduino/opencr/libraries/DynamixelSDK/src/dynamixel_sdk/port_handler_arduino.cpp#L184-L192
https://github.com/ROBOTIS-GIT/OpenCR/blob/28979242c9553cf46e819c575c57fb6db345dd5e/arduino/opencr_arduino/opencr/libraries/DynamixelSDK/src/dynamixel_sdk/port_handler_arduino.cpp#L290-L306

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
