### ISSUE TITLE
Maybe a bug ?

### ISSUE THREAD

**Issue by jacqu** [ROBOTIS-GIT/DynamixelSDK#21]
Hi,

In function port_handler_linux.c, this code seems strange to me:

      if (port_num == g_used_port_num)
    {
      for (port_num = 0; port_num < g_used_port_num; port_num++)
      {
        if (portData[port_num].socket_fd != -1)
          break;
      }

      if (port_num == g_used_port_num)
      {
        g_used_port_num++;
        portData = (PortData*)realloc(portData, g_used_port_num * sizeof(PortData));
        g_is_using = (uint8_t*)realloc(g_is_using, g_used_port_num * sizeof(uint8_t));
      }
    }

I think the test ` if (portData[port_num].socket_fd != -1)` should be ` if (portData[port_num].socket_fd == -1)` ?

Best,
Jacques

**Comment by ROBOTIS-Leon** [comment]
Hi!

You're right, I suppose. I'll test and update it after the vacation(~7.31.2016)
