### ISSUE TITLE
Cant get Dynamixel Matlab Comm working

### ISSUE THREAD

**Issue by TimmX9700** [ROBOTIS-GIT/DynamixelSDK#215]
I followed these instructions
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/matlab_windows/#run-example

Some colleagues could get it to work in Matlab 2018 for some reason

Dynamixel SDK 3.6.2

Using the lcc compiler with matlab R2013b in windows 7 32 bit

I have a USB2Dynamixel connected via TTL to three dynamixels AX-12A in series, which are then connected to a CM-510 for power

I get an error when compiling read_write:

> Warning: Message from C preprocessor:
> lcc preprocessor error: C:\Users\Don
> Krekler\Documents\MATLAB\dx\DynamixelSDK-3.6.2\c\include\dynamixel_sdk\packet_handler.h:24
> C:\Users\Don
> Krekler\Documents\MATLAB\dx\DynamixelSDK-3.6.2\c\include\dynamixel_sdk\group_bulk_read.h:25
> C:\Users\Don
> Krekler\Documents\MATLAB\dx\DynamixelSDK-3.6.2\c\include\dynamixel_sdk\dynamixel_sdk.h:24
> Could not find include file <stdint.h>
>  
> > In loadlibrary at 317
>   In read_write at 48 
> Error using loadlibrary (line 418)
> There was an error loading the library "C:\Users\Don
> Krekler\Documents\MATLAB\dx\DynamixelSDK-3.6.2\c\build\win32\output\dxl_x86_c.dll"
> No se puede encontrar el módulo especificado.
> 
> 
> 
> Error in read_write (line 48)
>     [notfound, warnings] = loadlibrary(lib_name, 'dynamixel_sdk.h', 'addheader',
>     'port_handler.h', 'addheader', 'packet_handler.h');
> 
> Caused by:
>     Error using loaddefinedlibrary
>     No se puede encontrar el módulo especificado.
>

**Comment by robotpilot** [comment]
@TimmX9700, This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
