### ISSUE TITLE
[3.6.2][MATLAB][USB2Dynamixel2][MX-64] Is there any way to command Two servos at the same time ?

### ISSUE THREAD

**Issue by kinter107** [ROBOTIS-GIT/DynamixelSDK#217]
Hi There,
I am commanding 2 servos in matlab and reading their present position and velocity using the following code :

[Sample_code.txt](https://github.com/ROBOTIS-GIT/DynamixelSDK/files/2249229/Sample_code.txt)

My problem is that using same codes for each servos doubles the time it takes to command and read from them.
i'm wondering if there is any other solution ( maybe some codes ) that can decrease the run time , for example commanding 2 servos with one piece of code and read from the again with one piece of code.
thank you.

**Comment by robotpilot** [comment]
Hi @kinter107,

I'm sorry for the late reply.
I recommend 'Sync Read and Sync Write Example'.  Unlike normal Read and Write, you will get what you want. See the link below for differences.

http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/faq/

http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/matlab_sync_read_write_protocol_2_0/#matlab-sync-read-write-protocol-20

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
