### ISSUE TITLE
Unclear tables in wiki

### ISSUE THREAD

**Issue by walchko** [ROBOTIS-GIT/DynamixelSDK#23]
Hello! I am confused by all of your tables in the wiki, such as this [one](https://github.com/ROBOTIS-GIT/DynamixelSDK/wiki/2.1-Dynamixel-Controller). Can you put a key somewhere (ideally on each table) saying what the X's, -'s, or O's mean? I am interested if this SDK works on the Raspberry Pi, but all I see are O's which might mean no. Thanks for the great work.

**Comment by ROBOTIS-Leon** [comment]
Hi!

Your advice is much appreciated.

Now you may find out what you wanted. I edited what you pointed out just now :)
SDK has been worked fine on Raspberry Pi since model 2B
We already tested it with C/C++/Python.

Any question during your work with SDK, let me know about it.
