### ISSUE TITLE
[Master][C++][USB2Dynamixel2][MX64] Issue : Implementing function block

### ISSUE THREAD

**Issue by serogamon** [ROBOTIS-GIT/DynamixelSDK#236]
- I'm using `DynamixelSDK ver. Master

- I'm using `C++` Language

- I'm using `USB2Dynamixel2` serial converter

- I'm using MX64

- and I'm having an `issue` like what:

I have a Simulink modell with Image acquisition and processing. I would like to implement a function block that the position of the motor react to the changing signal. How can i do this?

At first i´ve tried to controll the Dynamixel with a constant signal for the position like shown in the photos.

![1](https://user-images.githubusercontent.com/40755914/45423964-480d1780-b695-11e8-9fcd-9b0ef4d347ca.JPG)
![2](https://user-images.githubusercontent.com/40755914/45423965-480d1780-b695-11e8-9d9f-ba9076ea10b4.JPG)

But i get this Error:

![fehler](https://user-images.githubusercontent.com/40755914/45424020-7ab71000-b695-11e8-8a8d-a2318d6ed2aa.JPG)

**Comment by kijongGil** [comment]
Hi @serogamon :)
I'm sorry that I don't understand your situation.
Could you give me the more information??

**Comment by serogamon** [comment]
Hi, yes i´m able to controll the dynamixel with Matlab. I also tried to make my whole model with only Matlab, but here my problem is: i have to use a PID controller. In Simulink there is a PID block with an Input and an Output. When i use  the PID controller in Matlab i didn´t get a clear Output signal, only a transfer function. 
Maybe you know how to use this transfer function to controll the Dynamixel?

**Comment by kijongGil** [comment]
I'm sorry, but as we said, we do not support Simulink. Later, I will test whether it works in Simulink.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by lijing94123** [comment]
> I'm sorry, but as we said, we do not support Simulink. Later, I will test whether it works in Simulink.

Hi, may I know whether you've tested dynamixel motors in simulink and does it work?

Thank you!
