### ISSUE TITLE
[3.6.2][C][USB2AX][MX-28] Issue : Realloc fails, there is heap corruption somewhere

### ISSUE THREAD

**Issue by PeterMitrano** [ROBOTIS-GIT/DynamixelSDK#237]
DynamixelSDK ver. 3.6.2
C Language
Not sure, USB2AX I think?
MX-28

There is heap corruption somewhere, causing realloc to fail. full backtrace:

https://pastebin.com/raw/FxNW0jWW

**Comment by kijongGil** [comment]
Hi @PeterMitrano :)
Could you give me the more information? For example your IDE and what did you run code.
Thanks,

**Comment by PeterMitrano** [comment]
running directly in the terminal, using a python script that calls the C API for linux64. 

The error is difficult to reproduce, I'll try to come up with a short sample to reproduce the issue but it's difficult.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
