### ISSUE TITLE
Velocity Control in Dynamixel H430_W210R

### ISSUE THREAD

**Issue by hamidnrn** [ROBOTIS-GIT/DynamixelSDK#239]
ISSUE TEMPLATE ver. 1.1.1

Hello, I have an issue controling Dynamixel H430_W210R , i successfully could drive it using matlab protocol2 but I don't know know how to control the velocity ? it would be highly appreciated if somebody can help me

BE CAREFUL!! FOLLOW THE RULES AS FOLLOWS, OR YOUR ISSUE WILL BE `WON'T FIX` ANYWAY

STEP 1. Check what you are suffering from :

- I'm using `DynamixelSDK ver. 3.5.4`

  - [3.4.1], [3.5.2], etc.

- I'm using `C++` Language

  - [C] / [C++] / [C#] / [Python] / [Java] / [MATLAB] / [LABVIEW] / [ROS] / [Arduino]

- I'm using `USB2Dynamixel2` serial converter

  - [USB2Dynamixel] / [USB2Dynamixel2] or [OpenCM904] / [OpenCR] / [CM700s] / [CM500s] or other ROBOTIS product only

- I'm using `XM430-W210-R`

  - [MX-28], [AX-12W], [H54-200W], etc.

- and I'm having an `issue` like what

  - 'My motor doesn't work', etc.

STEP 2. Write `Title` as `[3.5.4][C++][USB2Dynamixel2][XM430-W210-R] Issue : My motor doesn't work`

- Now, if you think :

  - Hey, I'm using RoboPlus2.0, and having an issue, but how can I write that kind of `Title`?

  - Hey, I'm using USB2AX serial converter, and having an issue, but how can I write that kind of `Title`?

  - or more that is not listed on above.

- , You should write your `issue` on http://en.robotis.com/BlueAD/board.php?bbs_id=old_qna

STEP 3. Delete all written here, and describe what your problem is

- Any PICTURES or VIDEOS?

  ![](　Link the PICTURES or VIDEOS here, if necessary　)

- Any SOURCE SAMPLES?

  [](　Link the SOURCE SAMPLES here, if necessary　)

**Comment by kijongGil** [comment]
Hi @hamidnrn :)
Refer to control table : http://emanual.robotis.com/docs/en/dxl/x/xm430-w210/
There is Profile Velocity set to 0. You can control the velocity from it.

If you can move DXL using matlab read_write, just add follow code before while() line.
`write4ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 112, 100);`

112 is address of Profile Velocity, 100 is velocity data.

Thanks,
Gilbert

**Comment by hamidnrn** [comment]
Thanks for ur response,  but I don't need add present velocity and max and min in the code? Like present position, max and min ?

**Comment by kijongGil** [comment]
Sure, you can find out PID constants in control table.
Address of Position D Gain is 80. 
Address of Position I Gain is 82.
Address of Position P Gain is 84.
Also, you can change those same way.

**Comment by hamidnrn** [comment]
I really appreciate that, is it possible to change the mode in matlab ? similar code like this?
mode=input('ENTER MODE VALUE\n');  % mode can be 0 for current / 1 for velocity / 3 for position   
 write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 11, mode);
 
 
 if mode == 0        % current mode
     test=input('ENTER CURRENT VALUE\n');
     write2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 102, test);
    
 else if mode==1      %velocity mode
        
         test1=input('ENTER VALUE FOR VELOCITY\n');
         write2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 112, test1);
   
  else if mode==3      %position mode
          test2=input('ENTER VALUE FOR POSITION\n');
          write2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 116, test2);
      
    
 end

 i tried it but i couldn't

**Comment by robotpilot** [comment]
Hi @hamidnr,
The MATLAB code for Dynamixel is ready. Please refer to the document below. However, support for Simulink is not yet available.
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/matlab_windows/#matlab-windows
