### ISSUE TITLE
[3.6.0][ROS/C++][USB2Dynamixel][MX-106] Issue : Current-based position control causes motor overtorque

### ISSUE THREAD

**Issue by JoshMarino** [ROBOTIS-GIT/DynamixelSDK#240]
I am using Dynamixel Protocol 2.0 for MX-106 motors using ROS and C++ (dynamixel_workbench). I was under the impression that current-based position control acts like the position control mode, but will limit the amount of current (torque) to the Dynamixel. Under this assumption, the motor should never over-torque if the current limit I set using register "Goal_Current" is below the maximum rated current for the motor. Is this assumption right? If so, can you help me understand what I am doing wrong?

I am ROS launching position_control.launch with the following changes:

1. In the launch file I added a new ROS param for profile_current.

2. Under position_control.cpp, PositionControl(), I read the profile_current ROS param.

3. Under position_control.cpp, PositionControl(), I change jointMode() to currentMode() and pass in profile_current.

**Comment by kijongGil** [comment]
Hi @JoshMarino :)
I think your issue is not appropriate here. 
Please upload your issue to the [dynamixel-workbench](https://github.com/ROBOTIS-GIT/dynamixel-workbench/issues).
