### ISSUE TITLE
[3.5.4][python][USB2Dynamixel][mx64AR] Cannot build linux32 library

### ISSUE THREAD

**Issue by clarelywork** [ROBOTIS-GIT/DynamixelSDK#241]
Hello!

I am trying to connect a robot to raspiberry pi Model B through USB port, I have the v3.5.4 library on the raspi.
I have the script in Python, but the linux system is changed from linux64 to linux32.

Since I moved the script from a linux64 system, I cleared the makefile for linux64:

![raspi64](https://user-images.githubusercontent.com/40249278/45896611-8a1b1500-bd89-11e8-8f55-50106410acac.png)

then I went to linux32 folder and run:
$ make
and this is the result:

![raspi32](https://user-images.githubusercontent.com/40249278/45896677-b6cf2c80-bd89-11e8-8aa4-8a676a82f4bf.png)

Can you let me know how this can be solved?

Thank you!

**Comment by clarelywork** [comment]
Hello!

Someone from Robotis pointed out that if the date/time is not correct it might trow an error to the Makefile, so I corrected the time manually to match within 1 min error.
However, when I re-run the script, the error still exists:

![img_6082 1](https://user-images.githubusercontent.com/40249278/46042971-9544ac80-c0cb-11e8-95b7-7196f2924caf.JPG)

Please let me know how this can be resolved, thank you!

Clare

**Comment by ROBOTIS-zerom** [comment]
'-m32' tells the compiler to use and create 32bit objects, in contrast to '-m64' which would use/compile 64bit objects, and since the Pis ARM CPU only supports 32bit mode, both flags were left out.

just remove the '-m32' flag from Makefile and try again.

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while.
You can reopen this issue to show this issue to the users whenever.
Thanks.
