### ISSUE TITLE
[3.6.0][python][USB2DYNAMIXEL][MX64AR] AttributeError: 'Serial' object has no attribute 'reset_input_buffer'

### ISSUE THREAD

**Issue by clarelywork** [ROBOTIS-GIT/DynamixelSDK#242]
Hello!

I am trying to get a motor script running on RaspberryPi by connecting through USB port.
I am using SDK v3.6.0, in python on Raspi 32bit.
There are 2 MX64AR at baudrate 1M.

I followed the setup in this doc: http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/python_linux/ 

The motor script operates correctly when I run it on my linux laptop.
However, when I SSH into the raspi to run the script, this is the error I ran into: 
![serial](https://user-images.githubusercontent.com/40249278/45907368-7503ad80-bdac-11e8-80d1-16faac2f1d13.png)
\

Please let me know how I can resolve this. 

Thank you!

Clare

**Comment by kijongGil** [comment]
Hi @clarelywork :)

I'm sorry for late reply. This issue is that the SDK library path seems to be set up incorrectly.
Try the following command.
`sudo python [your script file] `

Thanks,
Gilbert.

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
