### ISSUE TITLE
Port still in use after keyboardexception

### ISSUE THREAD

**Issue by ShivangiMisra12** [ROBOTIS-GIT/DynamixelSDK#247]
I'm using DynamixelSDK in python. After interrupting a while loop with a keyboard exception, if I try to use the portHandler object to do anything, it responds with an error that says that the port is still in use. I have tried using portHandler.clear() to refresh the port. However, this doesn't seem to work either. I'de be grateful for any help regarding this issue.

**Comment by kijongGil** [comment]
Hi @ShivangiMisra12 :)
I'm sorry for late reply. I also know about this issue. Normally, when this happens, I reconnect the USB. But if you do not want this, I hope the this link will help you. https://unix.stackexchange.com/questions/355853/find-and-kill-the-process-that-is-using-a-serial-port

Thanks,
Gilbert

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
