### ISSUE TITLE
my_dynamixel_tutorial syntax error

### ISSUE THREAD

**Issue by msaufyrohmad** [ROBOTIS-GIT/DynamixelSDK#248]
ISSUE TEMPLATE ver. 

i encounter this problem when running my_dynamixel_tutorial. i need help 

NODES
  /
    dynamixel_manager (dynamixel_controllers/controller_manager.py)

ROS_MASTER_URI=http://localhost:11311

process[dynamixel_manager-1]: started with pid [18355]
  File "/opt/ros/kinetic/lib/dynamixel_controllers/controller_manager.py", line 210
    except ImportError, ie:
                      ^
SyntaxError: invalid syntax
================================================================================REQUIRED process [dynamixel_manager-1] has died!
process has died [pid 18355, exit code 1, cmd /opt/ros/kinetic/lib/dynamixel_controllers/controller_manager.py __name:=dynamixel_manager __log:=/home/husein/.ros/log/9c377c52-cdeb-11e8-be69-240a64b1d379/dynamixel_manager-1.log].
log file: /home/husein/.ros/log/9c377c52-cdeb-11e8-be69-240a64b1d379/dynamixel_manager-1*.log
Initiating shutdown!
================================================================================
[dynamixel_manager-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

BE CAREFUL!! FOLLOW THE RULES AS FOLLOWS, OR YOUR ISSUE WILL BE `WON'T FIX` ANYWAY

STEP 1. Check what you are suffering from :

- I'm using `DynamixelSDK ver. 3.5.4`

  - [3.4.1], [3.5.2], etc.

- I'm using `C++` Language

  - [C] / [C++] / [C#] / [Python] / [Java] / [MATLAB] / [LABVIEW] / [ROS] / [Arduino]

- I'm using `USB2Dynamixel2` serial converter

  - [USB2Dynamixel] / [USB2Dynamixel2] or [OpenCM904] / [OpenCR] / [CM700s] / [CM500s] or other ROBOTIS product only

- I'm using `XM430-W210-R`

  - [MX-28], [AX-12W], [H54-200W], etc.

- and I'm having an `issue` like what

  - 'My motor doesn't work', etc.

STEP 2. Write `Title` as `[3.5.4][C++][USB2Dynamixel2][XM430-W210-R] Issue : My motor doesn't work`

- Now, if you think :

  - Hey, I'm using RoboPlus2.0, and having an issue, but how can I write that kind of `Title`?

  - Hey, I'm using USB2AX serial converter, and having an issue, but how can I write that kind of `Title`?

  - or more that is not listed on above.

- , You should write your `issue` on http://en.robotis.com/BlueAD/board.php?bbs_id=old_qna

STEP 3. Delete all written here, and describe what your problem is

- Any PICTURES or VIDEOS?

  ![](　Link the PICTURES or VIDEOS here, if necessary　)

- Any SOURCE SAMPLES?

  [](　Link the SOURCE SAMPLES here, if necessary　)

**Comment by routiful** [comment]
Hi :)

If you have any question about dynamixel controller package, please use its issue page.
https://github.com/arebgun/dynamixel_motor/issues

I recommend that you can use [Dynamixel-Workbench](https://github.com/ROBOTIS-GIT/dynamixel-workbench) as ROBOTIS official package supporting X-serial Dynamixels.
