### ISSUE TITLE
There is no status packet! CM-530 and Ax-12A

### ISSUE THREAD

**Issue by sdereli** [ROBOTIS-GIT/DynamixelSDK#251]
hi.

I want to control my Ax-12A engine with the matlab program. 

controller: cm-530
SDK version: DynamixelSDK 3.5.4
protocol: 1.0

but I get this error: 
Succeeded to open the port!
Succeeded to change the baudrate!
[TxRxResult] There is no status packet!
Press any key to continue! (or input e to quit!)

[TxRxResult] There is no status packet!
[TxRxResult] There is no status packet!
[ID:009] GoalPos:000  PresPos:000
Press any key to continue! (or input e to quit!)

please help me.

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
