### ISSUE TITLE
[3.5.4][Arduino][openCR][XM430-W350-R] Firmware recovery using usb_to_dxl

### ISSUE THREAD

**Issue by truncs** [ROBOTIS-GIT/DynamixelSDK#252]
- I'm using `DynamixelSDK ver. 3.5.4`
- I'm using `Arduino` Language
- I'm using `OpenCR with usb_to_dxl` serial converter
- I'm using `XM430-W350-R`
- I was getting `no status packet` on testing the motor so I decided to do firmware recovery via openCR usb_to_dxl and R+ manager. But when I start the recovery procedure I just see orange light blinking on the openCR hardware and the recovery doesn't progress at all. I can post videos if that is helpful.

**Comment by kijongGil** [comment]
Hi @truncs :)
When you try to firmware recovery, The function of the OpenCR is just power source. 
Please refer to [this](http://emanual.robotis.com/docs/en/software/rplus2/manager/#advanced-features)

**Comment by truncs** [comment]
So I would still need additional hardware for flashing the firmware? I was following the guide mentioned in this comment 
https://github.com/ROBOTIS-GIT/OpenCR/issues/121#issuecomment-410591363

If that is not the case then I can buy the u2d2 adapter and then try it.

**Comment by kijongGil** [comment]
You can update firmware using OpenCR. When DXL and OpenCR are connected, if the red LED light on DXL(one time), the power is connected. Don't care light blinking of OpenCR.

By the way, if you continue to develop with DXL, it will be easier to buy and use u2d2.

**Comment by truncs** [comment]
I don't think I see the light blink on the DXL (even once). Here is my setup

- USB from laptop to openCR 
- 3 pin cable from openCR to to dxl
- turtlebot battery power

![img_20181022_234329](https://user-images.githubusercontent.com/157234/47341210-5451a080-d655-11e8-9e34-52a9d660e4e9.jpg)

**Comment by truncs** [comment]
Actually I used SMPS instead of the battery and it started working! Going to close this thread. Thanks!
