### ISSUE TITLE
[C],[XM430-W210-R],[U2D2] Issue: Is there a check for motor power cutoff?

### ISSUE THREAD

**Issue by karishmabava** [ROBOTIS-GIT/DynamixelSDK#254]
Hi ,
I am using C, XM430-W210-R and U2D2. Is there a check in the sdk that I can use for detecting power cut off and on in multiple motors?

--Karishma

**Comment by kijongGil** [comment]
Hi @karishmabava :)
Unfortunately, there is no detecting power cut off motor. You have to make a way to determine whether there is power by scanning the id of the motor or else.

Thanks,
Gilbert.
