### ISSUE TITLE
how to define inverse kinematics my robot arm (5 DOF)

### ISSUE THREAD

**Issue by sdereli** [ROBOTIS-GIT/DynamixelSDK#255]
Hi. I have successfully created and tested my custom robot and I have been able to edit its poses using the pose utility in RoboPlus Motion.
I would now like to add Inverse Kinematics to my robot as well. I have obtained the DH parameters of my robot and I want to define them in my robot. I read what information the e-manual had to offer from the following section.

Home > Software Help > RoboPlus > RoboPlus Motion > Extra Information > Making robots > Plug-In_SDK (http://support.robotis.com/en/software/roboplus/roboplus_motion/etc/userrobot/plug-in_sdk.htm)

I did step 1. Create Project, step 2. Add Reference, and step 3. Implement Interface. I did these steps correctly.

However steps 3.1, 3.2, 3.3, and 3.4 confuse me. I understand what each step does and why it is needed in the program. I do not understand how to actually add the values to the program to make it usable.﻿

help me please :)

**Comment by sdereli** [comment]
That's not what I want to say. There's no problem with my robot communicating with the computer. I created my own robot. In order for this robot to work the way I want it, it is necessary to introduce DH parameters to Roboplus with a DLL. How to do this is described in the Robotis E-Manual. However, I asked you for help because I do not fully understand what is described here. If there is an example made similar to this, I can do it by taking a sample. I hope I can tell you my problem.

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
