### ISSUE TITLE
[XM430-W350-R] use of Goal Velocity / Profile Acceleration / Profile Velocity

### ISSUE THREAD

**Issue by gooinc2** [ROBOTIS-GIT/DynamixelSDK#266]
Hello,

I am using XM430-W350-R motor.
Regarding the goal velocity, what's the default value range for XM430-W350-R?

2.2 Control Table of EEPROM Area
|Address | Size(Byte) | Data Name    | Access | DefaultValue | Range       | Unit                 |
|44         |              4 | Velocity Limit | RW      | 200              | 0 ~ 1,023 | 0.229 [rev/min]|

It looks that the default range is -200 ~ 200 based on the above table.
However, when I tested, it seems -350 ~ 350. 
It works for -350 ~ 350 and not for numbers greater than 350 or less than -350.

2.4.29 Goal Velocity (104)
|Unit           | Value Range                                        |
|0.229 rpm | -Velocity Limit(44) ~ Velocity Limit(44) |

2.4.16 Velocity Limit (44)
|Unit         | Value Range |
|0.229rpm | 0 ~ 1,023    |

In addition, could you please help me understand the followings? (http://emanual.robotis.com/docs/en/dxl/x/xm430-w350/)
1) Profile Acceleration(108)?
2) Profile Velocity(112)?

Thanks for your help.

**Comment by kijongGil** [comment]
Hi @gooinc2 :)
There are an explanation for those in [emanual](http://emanual.robotis.com/docs/en/dxl/x/xm430-w350/#profile-acceleration108).

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
