### ISSUE TITLE
[C++] [Arduino] [OpenCM904] Adding a "Freeze" feature to the SDK/servos

### ISSUE THREAD

**Issue by mtrossen** [ROBOTIS-GIT/DynamixelSDK#280]
Hello,

I'm posting a request for an addition of an important missing feature. Currently there is no way to tell a servo to stop moving and hold it's current position. Our team needs this feature to use on robotic arms. We need to be able to stop an arm or the arm gripper when sensors detect it is time to stop. 

For example, having an FSR in the gripper finger and sending a goal position to close the gripper, but once it grasps the object and the FSR indicates firm contact we then send the "freeze" command to the servo to stop it from closing further.

Another example would be using IR senors to detect position. Either to find an object to pick up, or collision detection for example. When the sensor signals to stop we could then tell all servos to freeze.

Another example would be a safety button. When pushed it freezes the arm in place.

Torquing off the servos isn't a solution of course because the whole are goes limp and comes crashing down. We have tried doing a very fast position read and sending a new goal position, but this doesn't work. The servo will continue moving for some time then reverse direction back to the new goal position. We need to be able to do an immediate freeze in place for an immediate stop and hold.

Thank you very much!

Matt

**Comment by kijongGil** [comment]
Hi @mtrossen :)
I understand what you want. Unfortunately, we don't have an instruction for freeze and plan to add that feature.
The best way now is to read current goal and write a new goal what you said.

Thanks,
Gilbert

**Comment by mtrossen** [comment]
HI Gilbert,

Thank you, I just wanted to make a thread for the new feature so I can track when it is added and to know that the team is working on it :)

Thanks!
Matt

**Comment by kijongGil** [comment]
Good job. I will close to this issue. If you have any question, please ask me.
Thanks.

**Comment by mtrossen** [comment]
Hi Gilbert,

Thank you for your response. I was posting this ticket so that it would remain open and be closed when the feature was added since Robotis is creating this feature. So closing it now won't inform me and other users when the feature is added. Shouldn't it remain "In Progress" until it is added?

Regards,

Matt
