### ISSUE TITLE
[3.5.4][C][U2D2][XM430-W210-R]Issue: Motor Power restart doesn't restart the motors movement.

### ISSUE THREAD

**Issue by karishmabava** [ROBOTIS-GIT/DynamixelSDK#282]
Hi,

I have an emergency stop installed on the motor chain. That is basically cutting the power supply off to the motors, but when I remove the e-stop/ start the power supply to the motors back up, the motor do not start moving. There is no TXRX errors that I get from write() or read().

Is there some firmware/hardware requirement that does not allow them to restart movement?

**Comment by kijongGil** [comment]
Hi, @karishmabava :)

Unfortunately, there is no function you said.
When DXL is powered off, data of control table is reset to default. So, DXL is not move when you start the power supply to the DXL back up.

If you want to use this function, you have to make bridge program.

Thanks,
Gilbert

**Comment by kijongGil** [comment]
That's good!
If you have any question, please ask me.
Thanks.
