### ISSUE TITLE
[3.5.4][Python][USB2Dynamixel2][XM430-W250-R] Issue: Overload at low present current value

### ISSUE THREAD

**Issue by gpicardi** [ROBOTIS-GIT/DynamixelSDK#285]
Hi, I have a problem with motor overloading and I do not understand why is this happening.

I am working in position control mode with 12V power supply and I command a position to my dynamixel. After some seconds (around 5s) keeping the desired position with a present current value of 350 (i.e. 941 mA) the motor goes into overload. Note that this always happens (Python, Matlab and R+ Manager).

Since the present current is much smaller than the stall current (which should be 2.3A at 12V according to the datasheet of the motor http://support.robotis.com/en/product/actuator/dynamixel_x/xm_series/xm430-w350.htm) and much smaller of the current limit (I am using the default value of 1193*2,69mA) I would like to know why is this happening.

What is the exact event that triggers the overload?

Please let me know if I gave enough information for answering and thanks in advance for your help .

Best, Giacomo

**Comment by kijongGil** [comment]
Hi, @gpicardi :)
When a high current flows for a few seconds, an overload occurs.
Could you tell me more detail your situation?
How to control position of DXL, and did you tried control DXL with no frame?

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
