### ISSUE TITLE
Torque Control Dynamixel MX106T

### ISSUE THREAD

**Issue by yildize** [ROBOTIS-GIT/DynamixelSDK#292]
Hey there, I want to drive dxl mx106t by torque mode. In one of the older issues, you have already specified that it can not be done directly by using python. Is it still the case? If it is, which language I can use in order to use torque mode.

**Comment by ROBOTIS-zerom** [comment]
Hello, yildize.

You can use python. 
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/python_read_write_protocol_1_0/#python-protocol-10

Referring to the read/write example, you can use the write1ByteTxRx function to write a value of 1 to address 70.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
