### ISSUE TITLE
[3.5.4][Python][OpenCM9.04][XL430-250] Issue : Update comment.

### ISSUE THREAD

**Issue by mwalkeriii** [ROBOTIS-GIT/DynamixelSDK#295]
Small correction in comment for Bulk Read/Write example. Line 127 in path DynamixelSDK/python/tests/protocol2_0/bulk_read_write.py is "# Enable Dynamixel#1 Torque" should be "# Enable Dynamixel#2 Torque"

**Comment by ROBOTIS-zerom** [comment]
OK, thank you. I'll fix it. :)
