### ISSUE TITLE
Request to reopen Issue #283

### ISSUE THREAD

**Issue by mtrossen** [ROBOTIS-GIT/DynamixelSDK#297]
Hello,

I have added a new post for issue #283 to reopen it. The developers should be able to repeat the bug now. I don't see anyway for me to reopen it myself.

[DynamixelSDK][Arduino][XL430-W250] Calling the SW Reset returns Error

https://github.com/ROBOTIS-GIT/DynamixelSDK/issues/283

Regards,

Matt

**Comment by mtrossen** [comment]
Hello,

It has been 48 days. Will someone please look at the issue of re-opening #238 and my post which shows how to repeat the bug?

Regards,

Matt

**Comment by ROBOTIS-zerom** [comment]
#283 reopened.
