### ISSUE TITLE
[3.5.4][MATLAB][UD2D][AX-12W] Issue: cannot write new position in velocity mode

### ISSUE THREAD

**Issue by salvatoreNRIM** [ROBOTIS-GIT/DynamixelSDK#299]
I am using a Dynamixel AX-12W. I am using Matlab, and USB2Dynamixel and my issue is that I cannot write new position (I am using the velocity mode). What I am trying to do with my motor is pretty simple: swinging from position 100 to 900 at constant speed. 
To do that I want to reset the position to 90 every time I start the script. However this line does not work for me:
write2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 30, 90);

Here the whole code

Here the script:

%%Swing protocol
% Here I have the swing swinging from -90 to +90 degrees back and forth.
% Where 0 is the vertical line

% Setting up communication with Dynamixel and parameters

clc;
% clear all;

lib_name = '';

if strcmp(computer, 'PCWIN')
    lib_name = 'dxl_x86_c';
elseif strcmp(computer, 'PCWIN64')
    lib_name = 'dxl_x64_c';
elseif strcmp(computer, 'GLNX86')
    lib_name = 'libdxl_x86_c';
elseif strcmp(computer, 'GLNXA64')
    lib_name = 'libdxl_x64_c';
elseif strcmp(computer, 'MACI64')
    lib_name = 'libdxl_mac_c';
end

% Load Libraries
if ~libisloaded(lib_name)
    [notfound, warnings] = loadlibrary(lib_name, 'dynamixel_sdk.h', 'addheader', 'port_handler.h', 'addheader', 'packet_handler.h');
end

% Control table address
ADDR_MX_TORQUE_ENABLE       = 24;           % Control table address is different in Dynamixel model
ADDR_MX_GOAL_POSITION       = 30;
ADDR_MX_PRESENT_POSITION    = 36;

ADDR_MX_CW = 6;
ADDR_MX_CCW = 8;
ADDR_MX_SPEED = 32;

% Protocol version
PROTOCOL_VERSION            = 1.0;          % See which protocol version is used in the Dynamixel

% Default setting
DXL_ID                      = 1;            % Dynamixel ID: 1
BAUDRATE                    = 1000000;
DEVICENAME                  = 'COM3';       % Check which port is being used on your controller
% ex) Windows: 'COM1'   Linux: '/dev/ttyUSB0' Mac: '/dev/tty.usbserial-*'

TORQUE_ENABLE               = 1;            % Value for enabling the torque
TORQUE_DISABLE              = 0;            % Value for disabling the torque
DXL_MINIMUM_POSITION_VALUE  = 100;          % Dynamixel will rotate between this value
DXL_MAXIMUM_POSITION_VALUE  = 4000;         % and this value (note that the Dynamixel would not move when the position value is out of movable range. Check e-manual about the range of the Dynamixel you use.)
DXL_MOVING_STATUS_THRESHOLD = 10;           % Dynamixel moving status threshold

ESC_CHARACTER               = 'e';          % Key for escaping loop

COMM_SUCCESS                = 0;            % Communication Success result value
COMM_TX_FAIL                = -1001;        % Communication Tx Failed

% Initialize PortHandler Structs
% Set the port path
% Get methods and members of PortHandlerLinux or PortHandlerWindows
port_num = portHandler(DEVICENAME);

% Initialize PacketHandler Structs
packetHandler();

index = 1;
dxl_comm_result = COMM_TX_FAIL;             % Communication result
dxl_goal_position = [DXL_MINIMUM_POSITION_VALUE DXL_MAXIMUM_POSITION_VALUE];         % Goal position

dxl_error = 0;                              % Dynamixel error
dxl_present_position = 0;                   % Present position

% Open port
if (openPort(port_num))
    fprintf('Succeeded to open the port!\n');
else
    unloadlibrary(lib_name);
    fprintf('Failed to open the port!\n');
    input('Press any key to terminate...\n');
    return;
end

% Set port baudrate, that is sets the comunication with the motor
if (setBaudRate(port_num, BAUDRATE))
    fprintf('Succeeded to change the baudrate!\n');
else
    unloadlibrary(lib_name);
    fprintf('Failed to change the baudrate!\n');
    input('Press any key to terminate...\n');
    return;
end

% Enable Dynamixel Torque, that is, motor is ready to move
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, ADDR_MX_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel has been successfully connected \n');
end
%% Program motor movement, Tx =transmission, Rx = reception
n = 0;
while n <40 %this corresponds to 10 swings
    dxl_present_position = read2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, ADDR_MX_PRESENT_POSITION);
    fprintf('[ID:%03d] GoalPos:%03d  PresPos:%03d\n', DXL_ID, dxl_goal_position(index), dxl_present_position);
    %for an angle less than 100/1024 rotate CCW:
    if dxl_present_position <100
        write2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 32, 150);
        n = n+1;
    %for an angle more than 900/1024 rotate CW:
    elseif dxl_present_position >900
        write2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 32, 1174);   
        n = n+1;
    %This should move the position to 90, for now
    %I will do it manually
    else
        dxl_present_position = 90;
        write2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 30, 90);
    end
end
%After 10 swings set speed to 0
write2ByteTxRx(port_num, PROTOCOL_VERSION, DXL_ID, 32, 0);

**Comment by ROBOTIS-zerom** [comment]
You say you're using velocity mode. 
Does velocity mode mean Wheel Mode?? (Both CW/CCW Angle Limit values are 0.)

If it is set to Wheel Mode, Goal Position(30) value is not used.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
