### ISSUE TITLE
The same code that works in Windows does not work in Ubuntu

### ISSUE THREAD

**Issue by wayneyzt** [ROBOTIS-GIT/DynamixelSDK#300]
- I'm using `C++` Language

- I'm using `USB2Dynamixel2` serial converter

- I'm using `XM430-W350-T`

- My problem is  that I wrote a program that can control the openmanipulator arm to play ping-pong ball up and down. I did it in Windows Visual Studio, and it perfectly run. However, for some reason I need to transplant my code to Ubuntu 16.04. Here is the problem, the same code does not work.

This is part of the code:

in .h file:
void controlToolBox::setGoalPosition(int8_t id, int16_t value)
{
	dxl_addparam_result = bulkWrite->addParam(id, ADDR_GOAL_POSITION, LEN_GOAL_POSITION, (uint8_t *)&value);
	if (dxl_addparam_result)
	{
		bulkWrite->txPacket();
		bulkWrite->clearParam();
	}
	else
	{
		printf("set goal position failed!!!\n");
		return;
	}
}

in .cpp file:

void rectHit(float digit, float vel) {
	
	ctb.setGoalPosition(3, 1536 + digit);

	ctb.setGoalPosition(4, 2048 + digit );

	while (ctb.getPresentPosition(3) <= 1536 + digit + 50 &&
		ctb.getPresentPosition(3) >= 1536 + digit - 50 &&
		ctb.getPresentPosition(4) <= 2048 + digit + 20 &&
		ctb.getPresentPosition(4) >= 2048 + digit - 20)
	{
		cout << "==============" << endl;
		ctb.setGoalVelocity(3, vel);
		ctb.setGoalPosition(4, 2048 - digit + 50);
		ctb.setGoalPosition(3, 1536 - digit);
		while (ctb.getPresentPosition(3) > 1536 - digit) {
			cout << "wait" << endl;
		}
	}

}

The problem is this code in Ubuntu can get the arm to get to the first position(means 	ctb.setGoalPosition(3, 1536 + digit);  this line worked and the rest did not work
) and then it stopped. It worked in Windows Visual Studio.
Any help would be appreciated.

**Comment by ROBOTIS-zerom** [comment]
I'm sorry. We can debug the code in the Dynamixel SDK, but it is difficult to help you debug your own code.
