### ISSUE TITLE
[3.7.0][MATLAB][USB2Dynamixel2][XL430-W2250] Issue : groupSyncWrite not in library

### ISSUE THREAD

**Issue by bambz96** [ROBOTIS-GIT/DynamixelSDK#303]
Hi there, 
I'm trying to use the Group Sync Write functionality however I'm getting an error in MATLAB saying the method was not found (see below). 
![image](https://user-images.githubusercontent.com/21301201/56730299-fab06700-679a-11e9-88c3-183beabbe15e.png)
I did a library function search to see whether the method is listed but noticed it isn't and there aren't any of the group functions available (see below) 
![image](https://user-images.githubusercontent.com/21301201/56730344-1e73ad00-679b-11e9-9fdd-a8ac5e81cdca.png)
I've also tried using the example Matlab script but I'm getting the same issue. Also note that other functionality is fine, I have no trouble sending individual commands however I'd like to use the Sync functionality to speed things up. 
Thanks, 
Bambz

**Comment by ROBOTIS-zerom** [comment]
Hi, Bambz.

I have found that the library file & dll file in C language is outdated. 
I rebuild and uploaded it to the latest file.
The old file is missing the "clearMultiTurn" function.

Try again with the latest in the master branch.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by KartikeyaWalia** [comment]
Hello,

I am having the same issue and with the latest version of the SDK it is still showing 'group SyncWrite' isn't there in the library. I have checked and verified that it is missing. 
![image](https://user-images.githubusercontent.com/62836634/182417820-ce487da1-4aec-4cb6-ab03-6a341ddc70cf.png)
Please respond.
