### ISSUE TITLE
[3.7.0][Python][U2D2][XL430-W250-T/AX-12A] Connecting both servos to the same chain. 

### ISSUE THREAD

**Issue by kcsss** [ROBOTIS-GIT/DynamixelSDK#308]
- I'm using `DynamixelSDK ver. 3.7.0`

- I'm using `Python` Language

- I'm using `U2D2` serial converter

- I'm using `XL430-W250-T` - `AX-12A`

- and I'm having an `issue` like what

 I'm trying to connect both models on the same daisy chain (4 XL and 1 AX ), I read that the protocol are different, so I'm coding in Python a program that can talk both protocols. The example of multi-protocol opens two ports, and reads/write separately to them, its is possible to make this using only one port (say for example COM12 where the U2D2 controller is connected). Has anyone made this task before or it is impossible to make this ?.

Best regards.

**Comment by ROBOTIS-zerom** [comment]
Hi, kcsss.

You can use both protocols in languages other than Python. 
And the example of multi-protocol (example name : protocol_combined) opens just one port.
Check the example code again..

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
