### ISSUE TITLE
[3.6.0][MATLAB][OPENCM904][OpenCM485EXP][XH430-W350] Issue: Sending commands to OpenCM485

### ISSUE THREAD

**Issue by ShuoqiChen** [ROBOTIS-GIT/DynamixelSDK#309]
Hi, 

I have tried using the sample code for MATLAB with the Dynamixel SDK to control a XH430-W350. I am able to connect to establish a connection, however, I can't read or write anything afterwards. 

Currently the OpenCM485 is connected to the OPENCM904 in the configuration shown here:
http://emanual.robotis.com/docs/en/parts/controller/opencm485exp/#connecting-opencm904

This is the error I am receiving from MATLAB:
Succeeded to open the port!
Succeeded to change the baudrate!
[TxRxResult] There is no status packet!
Press any key to continue! (or input e to quit!)

Any insight is greatly appreciated

**Comment by ROBOTIS-zerom** [comment]
Hi, ShuoqiChen.

In that link, You have to program using the Arduino IDE, not MATLAB. 
(Firmware programming)

OpenCM9.04 is not a USB to Serial device. 
U2D2 is recommended.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
