### ISSUE TITLE
[3.5.4][MATLAB][UD2D][AX-12W] Issue: call to Perl failed

### ISSUE THREAD

**Issue by salvatoreNRIM** [ROBOTIS-GIT/DynamixelSDK#310]
I am using a Dynamixel AX-12W. I am using Matlab 2016b, and USB2Dynamixel and my issue is that I keep getting the error "Call to Perl failed. Possible error processing header file." Even when running the read_write file.
However I checked, and I have Perl in my matlab folder. Does anybody have encountered this issue and know how to solve it?

**Comment by ROBOTIS-zerom** [comment]
Hi, salvatore.

I think it is MATLAB problem. Check the MATLAB answers..

https://www.mathworks.com/matlabcentral/answers/?term=Call+to+Perl+failed.+Possible+error+processing+header+file.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
