### ISSUE TITLE
> I'm sorry, but as we said, we do not support Simulink. Later, I will test whether it works in Simulink.

### ISSUE THREAD

**Issue by lijing94123** [ROBOTIS-GIT/DynamixelSDK#311]
> I'm sorry, but as we said, we do not support Simulink. Later, I will test whether it works in Simulink.

Hi, may I know whether you've tested dynamixel motors in simulink and does it work?
Is there any package of dynamixel motors for simulink now?

Thank you!

_Originally posted by @lijing94123 in https://github.com/ROBOTIS-GIT/DynamixelSDK/issues/236#issuecomment-500786093_

**Comment by lijing94123** [comment]
And by directly connecting dynamixel motors with PC through USB2Dynamixel2.

**Comment by kijongGil** [comment]
Hi, @lijing94123 
I'm sorry, but did not tested because not yet decided to support the Simulink.

**Comment by lijing94123** [comment]
I see. Thank you!
