### ISSUE TITLE
[USB2Dynamixel][MATLAB][MX-64AT] Issue: Latency too high

### ISSUE THREAD

**Issue by PedroLehigh** [ROBOTIS-GIT/DynamixelSDK#316]
Hi, 

I'm using the same computer with the same hardware (USB2Dynamixel) to control a single MX_64AT using Protocol 1.0. 

I am generating an array with positions to create sinusoidal motion. With one of my servos I am able to send a new signal every 0.002 seconds making the motion smooth. However, when I switch to another MX_64AT servo, the minimum time I have to wait between 2 positions is 0.038 seconds. The baud rate is set to 1 million for both servos. I am NOT controlling them at the same time. 
I do not understand why one of the servos has such a high latency while the other is working perfectly fine. 

Please help me. The same issue happens when controling it from Arduino.

**Comment by ROBOTIS-zerom** [comment]
Hello, Pedro Lehigh.

If you use windows, 
1. Change USB latency settings ( to 1msec ) : http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#usb-latency-setting
2. Firmware recovery : http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#firmware-recovery
3. Set the return delay time value of the control table to 0.
4. Please let us know the time of the instruction packet and the status packet in the packet window:
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#packet-window

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
