### ISSUE TITLE
RxPacketError 문의

### ISSUE THREAD

**Issue by supermandugi** [ROBOTIS-GIT/DynamixelSDK#32]
예제 코드 c++, matlab 모두 아래 에러가 발생합니다.
[RxPacketError] The data value is out of range!

오류 이후에 R+ manager 2.0으로 동작하는 것을 확인했고 펌웨어 복구후에도 같은 에러를 확인하였습니다. 또 확인할 것이 있을까요?

**Comment by ROBOTIS-Leon** [comment]
[Please note] Q&A in Korean is being serviced by contacting with support@robotis.com or [Q&A bulletin board](http://www.robotis.com/BlueAD/board.php?bbs_id=board_02).

[The question] was that there is some errors referring "[RxPacketError] The data value is out of range!" on the example codes in c++ and Matlab.

[Reply] Check if you read inadequate length of bytes from the item listed on the control table (see support.robotis.com). Which means, it could be occurred when the value you need is shorter than expected by the Dynamixel side.
