### ISSUE TITLE
[Arduino][OpenCM904][DynamixelSDK][MX64AR &RX24F]Motors read in present position but do not write

### ISSUE THREAD

**Issue by JPierceRobotics** [ROBOTIS-GIT/DynamixelSDK#325]
Hi,

I'm on Ubuntu 16.04 using Arduino 1.8.5, DynamixelSDK and Workbench, OpenCM and a few different models of Dynamixel but the ones I'm just trying to get to work now are MX64AR and RX24F.

I've tried different codes to try to get the bulkwrite working. The motors move fine when run using the plain goal position examples.

The DynamixelSDK bulkwrite example doesn't move the motors.

The Workbench bulkwrite example below doesn't move the motors either and gives the error: 

> 
> groupBulkWrite addparam failed
> Failed to add bulk write position param
> groupBulkWrite addparam failed
> Failed to add bulk write led param
> [TxRxResult] Protocol does not support This function!
> Failed to bulk write
> [TxRxResult] There is no status packet!
> Failed to bulk read
> groupBulkRead getdata failed
> 

Code:

`#include <DynamixelWorkbench.h>`

`#if defined(__OPENCM904__)`
`  #define DEVICE_NAME "3" //Dynamixel on Serial3(USART3)  <-OpenCM 485EXP`
`#elif defined(__OPENCR__)`
`  #define DEVICE_NAME ""`
`#endif   `

`#define BAUDRATE  1000000`
`#define DXL_ID_1  2`
`#define DXL_ID_2  3`

`DynamixelWorkbench dxl_wb;`

`uint8_t dxl_id[2] = {DXL_ID_1, DXL_ID_2};`
`int32_t goal_position[2] = {0, 1023};`
`int32_t led[2] = {0, 1};`

`const uint8_t handler_index = 0;`

`void setup() `
`{`
`  Serial.begin(57600);`
`  while(!Serial); // Wait for Opening Serial Monitor`

 ` const char *log;`
 ` bool result = false;`

`  uint16_t model_number = 0;`

 ` result = dxl_wb.init(DEVICE_NAME, BAUDRATE, &log);`
`  if (result == false)`
 ` {`
 `   Serial.println(log);`
 `   Serial.println("Failed to init");`
  `}`
`  else`
 ` {`
  `  Serial.print("Succeeded to init : ");`
 `   Serial.println(BAUDRATE);  `
 ` }

`  for (int cnt = 0; cnt < 2; cnt++)`
`  {`
`    result = dxl_wb.ping(dxl_id[cnt], &model_number, &log);`
`    if (result == false)`
`    {`
`      Serial.println(log);`
`     Serial.println("Failed to ping");`
`    }`
`    else`
`    {`
`      Serial.println("Succeeded to ping");`
`      Serial.print("id : ");`
`      Serial.print(dxl_id[cnt]);`
`      Serial.print(" model_number : ");`
`      Serial.println(model_number);`
`    }`

`    result = dxl_wb.jointMode(dxl_id[cnt], 0, 0, &log);`
`    if (result == false)`
`    {`
`      Serial.println(log);`
 `     Serial.println("Failed to change joint mode");`
`    }`
`    else`
`    {`
`      Serial.println("Succeed to change joint mode");`
`    }`
`  } `

 ` result = dxl_wb.initBulkWrite(&log);`
`  if (result == false)`
`  {`
`    Serial.println(log);`
`  }`
`  else`
`  {`
`    Serial.println(log);`
`  }`

`  result = dxl_wb.initBulkRead(&log);`
`  if (result == false)`
`  {`
`    Serial.println(log);`
`  }`
`  else`
`  {`
`    Serial.println(log);`
`  }`

`  result = dxl_wb.addBulkReadParam(dxl_id[0], "Present_Position", &log);`
`  if (result == false)`
`  {`
`    Serial.println(log);`
`    Serial.println("Failed to add bulk read position param");`
`  }`
`  else`
`  {`
`    Serial.println(log);`
`  }`

`  result = dxl_wb.addBulkReadParam(dxl_id[1], "LED", &log);`
`  if (result == false)`
`  {`
`    Serial.println(log);`
`    Serial.println("Failed to add bulk read led param");`
`  }`
`  else`
`  {`
`    Serial.println(log);`
`  }`
`}`

`void loop() `
`{  `
`  delay(10000);`
`  const char *log;`
`  bool result = false;`
`  `
`  int32_t get_data[2] = {0, 0};`

`  result = dxl_wb.addBulkWriteParam(dxl_id[0], "Goal_Position", goal_position[0], &log);`
`  if (result == false)`
`  {`
`    Serial.println(log);`
`    Serial.println("Failed to add bulk write position param");`
`  }`
`  else`
`  {`
`    Serial.println(log);`
`  }`

`  result = dxl_wb.addBulkWriteParam(dxl_id[1], "LED", led[0], &log);`
`  if (result == false)`
`  {`
`    Serial.println(log);`
`    Serial.println("Failed to add bulk write led param");`
`  }`
`  else`
`  {`
`    Serial.println(log);`
`  }`

`  result = dxl_wb.bulkWrite(&log);`
`  if (result == false)`
`  {`
`    Serial.println(log);`
`    Serial.println("Failed to bulk write");`
`  }`

`  do`
`  {`
`    result = dxl_wb.bulkRead(&log);`
`    if (result == false)`
`    {`
`      Serial.println(log);`
`      Serial.println("Failed to bulk read");`
`    }`

`    result = dxl_wb.getBulkReadData(&get_data[0], &log);`
`    if (result == false)`
`    {`
`      Serial.println(log);`
`    }`
`    else`
`    {`
`      Serial.print("[ID ");`
`      Serial.print(dxl_id[0]);`
`      Serial.print(" ]");`
`      Serial.print(" Goal Position : ");`
`      Serial.print(goal_position[0]);`
`      Serial.print(" Present Position : ");`
`      Serial.print(get_data[0]);`
`      Serial.print(" [ID ");`
`      Serial.print(dxl_id[1]);`
`      Serial.print(" ]");`
`      Serial.print(" Goal LED : ");`
`      Serial.println(get_data[1]);`
      
`    }`

`  }while(abs(goal_position[0] - get_data[0]) > 15);`

`  swap(goal_position);`
`  swap(led);`
  
`}`

`void swap(int32_t *array)`
`{`
`  int32_t tmp = array[0];`
`  array[0] = array[1];`
`  array[1] = tmp;`
`}`

**Comment by ROBOTIS-zerom** [comment]
Hello, 

Bulk Write instruction is not available in Dynamixel Protocol 1.0
and Bulk Read instruction is only available for the MX series.

check below link:
http://emanual.robotis.com/docs/en/dxl/protocol1/#instruction

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
