### ISSUE TITLE
groupsyncread  detdata failed of 8 dynamixel XM430-W350_T using matlab

### ISSUE THREAD

**Issue by areej1980** [ROBOTIS-GIT/DynamixelSDK#327]
ISSUE TEMPLATE ver. 1.1.1

why do I get this error message when I operate 8 8 dynamixel XM430-W350_T using matlab
 [TxRxResult] Incorrect status packet!
[ID:001] groupSyncRead getdata failed>>
 
I use the same example of Matlab Sync Read Write Protocol 2.0

BE CAREFUL!! FOLLOW THE RULES AS FOLLOWS, OR YOUR ISSUE WILL BE `WON'T FIX` ANYWAY

STEP 1. Check what you are suffering from :

- I'm using `DynamixelSDK ver. 3.5.4`

  - [3.4.1], [3.5.2], etc.

- I'm using `C++` Language

  - [C] / [C++] / [C#] / [Python] / [Java] / [MATLAB] / [LABVIEW] / [ROS] / [Arduino]

- I'm using `USB2Dynamixel2` serial converter

  - [USB2Dynamixel] / [USB2Dynamixel2] or [OpenCM904] / [OpenCR] / [CM700s] / [CM500s] or other ROBOTIS product only

- I'm using `XM430-W210-R`

  - [MX-28], [AX-12W], [H54-200W], etc.

- and I'm having an `issue` like what

  - 'My motor doesn't work', etc.

STEP 2. Write `Title` as `[3.5.4][C++][USB2Dynamixel2][XM430-W210-R] Issue : My motor doesn't work`

- Now, if you think :

  - Hey, I'm using RoboPlus2.0, and having an issue, but how can I write that kind of `Title`?

  - Hey, I'm using USB2AX serial converter, and having an issue, but how can I write that kind of `Title`?

  - or more that is not listed on above.

- , You should write your `issue` on http://en.robotis.com/BlueAD/board.php?bbs_id=old_qna

STEP 3. Delete all written here, and describe what your problem is

- Any PICTURES or VIDEOS?

  ![](　Link the PICTURES or VIDEOS here, if necessary　)

- Any SOURCE SAMPLES?

  [](　Link the SOURCE SAMPLES here, if necessary　)

**Comment by areej1980** [comment]
I use sdk matlab master, U2D2 interface device, 
8 dynamixel XM430-W350_T
BAUDRATE                    = 57600;
I use the same example of Matlab Sync Read Write Protocol 2.0

and each time I operate the example I get the same error
[TxRxResult] Incorrect status packet!
[ID:001] groupSyncRead getdata failed>>
can any one help me please

my program is below


clc;
clear all;

lib_name = '';

if strcmp(computer, 'PCWIN')
  lib_name = 'dxl_x86_c';
elseif strcmp(computer, 'PCWIN64')
  lib_name = 'dxl_x64_c';
elseif strcmp(computer, 'GLNX86')
  lib_name = 'libdxl_x86_c';
elseif strcmp(computer, 'GLNXA64')
  lib_name = 'libdxl_x64_c';
elseif strcmp(computer, 'MACI64')
  lib_name = 'libdxl_mac_c';
end

% Load Libraries
if ~libisloaded(lib_name)
    [notfound, warnings] = loadlibrary(lib_name, 'dynamixel_sdk.h', 'addheader', 'port_handler.h', 'addheader', 'packet_handler.h', 'addheader', 'group_sync_write.h', 'addheader', 'group_sync_read.h');
end

% Control table address
ADDR_PRO_TORQUE_ENABLE          = 64;                 % Control table address is different in Dynamixel model
ADDR_PRO_GOAL_POSITION          = 116;
ADDR_PRO_PRESENT_POSITION       = 132;

% Data Byte Length
LEN_PRO_GOAL_POSITION       = 4;
LEN_PRO_PRESENT_POSITION    = 4;

% Protocol version
PROTOCOL_VERSION            = 2.0;          % See which protocol version is used in the Dynamixel

% Default setting
DXL1_ID                     = 1;            % Dynamixel#1 ID: 1
DXL2_ID                     = 2;            % Dynamixel#2 ID: 2
DXL3_ID                     = 3;            % Dynamixel#1 ID: 3
DXL4_ID                     = 4;            % Dynamixel#2 ID: 4
DXL5_ID                     = 5;            % Dynamixel#2 ID: 4
DXL6_ID                     = 6;            % Dynamixel#1 ID: 3
DXL7_ID                     = 7;            % Dynamixel#2 ID: 4
DXL8_ID                     = 8;            % Dynamixel#2 ID: 4

BAUDRATE                    = 57600;
DEVICENAME                  = 'COM3';       % Check which port is being used on your controller
                                            % ex) Windows: 'COM1'   Linux: '/dev/ttyUSB0' Mac: '/dev/tty.usbserial-*'

TORQUE_ENABLE               = 1;            % Value for enabling the torque
TORQUE_DISABLE              = 0;            % Value for disabling the torque

DXL_MOVING_STATUS_THRESHOLD = 20;           % Dynamixel moving status threshold

ESC_CHARACTER               = 'e';          % Key for escaping loop

COMM_SUCCESS                = 0;            % Communication Success result value
COMM_TX_FAIL                = -1001;        % Communication Tx Failed

% Initialize PortHandler Structs
% Set the port path
% Get methods and members of PortHandlerLinux or PortHandlerWindows
port_num = portHandler(DEVICENAME);

% Initialize PacketHandler Structs
packetHandler();

% Initialize Groupsyncwrite Structs
groupwrite_num = groupSyncWrite(port_num, PROTOCOL_VERSION, ADDR_PRO_GOAL_POSITION, LEN_PRO_GOAL_POSITION);

% Initialize Groupsyncread Structs for Present Position
groupread_num = groupSyncRead(port_num, PROTOCOL_VERSION, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

index = 1;
dxl_comm_result = COMM_TX_FAIL;           % Communication result
dxl_addparam_result = false;              % AddParam result
dxl_getdata_result = false;               % GetParam result

dxl_error = 0;                              % Dynamixel error
dxl_present_position1 = 0;                  % Present position
dxl_present_position2 = 0;
dxl_present_position3 = 0;                  % Present position
dxl_present_position4 = 0;
dxl_present_position5 = 0;
dxl_present_position6 = 0;                  % Present position
dxl_present_position7 = 0;
dxl_present_position8 = 0;

% Open port
if (openPort(port_num))
    fprintf('Succeeded to open the port!\n');
else
    unloadlibrary(lib_name);
    fprintf('Failed to open the port!\n');
    input('Press any key to terminate...\n');
    return;
end


% Set port baudrate
if (setBaudRate(port_num, BAUDRATE))
    fprintf('Succeeded to change the baudrate!\n');
else
    unloadlibrary(lib_name);
    fprintf('Failed to change the baudrate!\n');
    input('Press any key to terminate...\n');
    return;
end


% Enable Dynamixel#1 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL1_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL1_ID);
end

% Enable Dynamixel#2 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL2_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL2_ID);
end

% Enable Dynamixel#3 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL3_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL3_ID);
end

% Enable Dynamixel#4 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL4_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL4_ID);
end

% Enable Dynamixel#5 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL5_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL5_ID);
end

% Enable Dynamixel#6 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL6_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL6_ID);
end

% Enable Dynamixel#7 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL7_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL7_ID);
end

% Enable Dynamixel#8 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL8_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_ENABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
else
    fprintf('Dynamixel #%d has been successfully connected \n', DXL8_ID);
end



% Add parameter storage for Dynamixel#1 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL1_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL1_ID);
  return;
end

% Add parameter storage for Dynamixel#2 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL2_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL2_ID);
  return;
end

% Add parameter storage for Dynamixel#3 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL3_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL3_ID);
  return;
end

% Add parameter storage for Dynamixel#4 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL4_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL4_ID);
  return;
end

% Add parameter storage for Dynamixel#5 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL5_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL5_ID);
  return;
end

% Add parameter storage for Dynamixel#6 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL6_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL6_ID);
  return;
end

% Add parameter storage for Dynamixel#7 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL7_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL7_ID);
  return;
end

% Add parameter storage for Dynamixel#8 present position value
dxl_addparam_result = groupSyncReadAddParam(groupread_num, DXL8_ID);
if dxl_addparam_result ~= true
  fprintf('[ID:%03d] groupSyncRead addparam failed', DXL8_ID);
  return;
end

a=45*pi/180; w=90*pi/180; L=90.5*pi/180; delta=0.1;l=75/2000; N=4; kp=20; kd=5; Qo=0; kQ=0.3 ;E1=0 ;E2=0; E3=0; E4=0; E5=0; E6=0; E7=0; E8=0;
 QN=0; py2=0; px2=0; py1=0; px1=0;

while 1
    if input('Press any key to continue! (or input e to quit!)\n', 's') == ESC_CHARACTER
        break;
    end
    
   for t=0:10
     py1=py2-py1
    px1=px2-px1
    q=atan(py1/px1)
    if t==0
        J(1)=2000; J(2)=2000; J(3)=2000; J(4)=2000; J(5)=0; J(6)=2000; J(7)=2000; J(8)=0;
    else
 for i=1:8
   
     Q(i)=a*sin(w*t+(i-1)*L)+q*pi/180;
     
   
     Q2(i)=fix(Q(i)*100);
     x(i)=Q2(i)*(2000/181)+2000;
      J(i)=fix(x(i));     
 end 
    end
    

           
        J1=J(1)+E1;
        J2=J(2)+E2;
        J3=J(3)+E3;
        J4=J(4)+E4;
        J5=J(5)+E5;
        J6=J(6)+E6;
        J7=J(7)+E7;
        J8=J(8)+E8;
             
              dxl_goal_position1 = [J1 J1];         % Goal position dynamixel1
            dxl_goal_position2 = [J2 J2];         % Goal position dynamixel 2
            dxl_goal_position3 = [J3 J3];         % Goal position dynamixel 3
             dxl_goal_position4 = [J4 J4];         % Goal position dynamixel 4
              dxl_goal_position5 = [J5 J5];         % Goal position dynamixel 4
              dxl_goal_position6 = [J6 J6];         % Goal position dynamixel 4
              dxl_goal_position7 = [J7 J7];         % Goal position dynamixel 4
              dxl_goal_position8 = [J8 J8];         % Goal position dynamixel 4
             
 
 
 

    % Add Dynamixel#1 goal position value to the Syncwrite storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL1_ID, typecast(int32(dxl_goal_position1(index)), 'uint32'), LEN_PRO_GOAL_POSITION);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL1_ID);
        return;
    end

    % Add Dynamixel#2 goal position value to the Syncwrite parameter storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL2_ID, typecast(int32(dxl_goal_position2(index)), 'uint32'), LEN_PRO_GOAL_POSITION);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL2_ID);
        return;
    end
    
     % Add Dynamixel#3 goal position value to the Syncwrite storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL3_ID, typecast(int32(dxl_goal_position3(index)), 'uint32'), LEN_PRO_GOAL_POSITION);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL3_ID);
        return;
    end

    % Add Dynamixel#4 goal position value to the Syncwrite parameter storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL4_ID, typecast(int32(dxl_goal_position4(index)), 'uint32'), LEN_PRO_GOAL_POSITION);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL4_ID);
        return;
    end
    
     % Add Dynamixel#5 goal position value to the Syncwrite storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL5_ID, typecast(int32(dxl_goal_position5(index)), 'uint32'), LEN_PRO_GOAL_POSITION);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL5_ID);
        return;
    end

% Add Dynamixel#6 goal position value to the Syncwrite storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL6_ID, typecast(int32(dxl_goal_position6(index)), 'uint32'), LEN_PRO_GOAL_POSITION);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL6_ID);
        return;
    end

    % Add Dynamixel#7 goal position value to the Syncwrite parameter storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL7_ID, typecast(int32(dxl_goal_position7(index)), 'uint32'), LEN_PRO_GOAL_POSITION);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL7_ID);
        return;
    end
    
     % Add Dynamixel#8 goal position value to the Syncwrite storage
    dxl_addparam_result = groupSyncWriteAddParam(groupwrite_num, DXL8_ID, typecast(int32(dxl_goal_position8(index)), 'uint32'), LEN_PRO_GOAL_POSITION);
    if dxl_addparam_result ~= true
        fprintf('[ID:%03d] groupSyncWrite addparam failed', DXL8_ID);
        return;
    end
    % Syncwrite goal position
    groupSyncWriteTxPacket(groupwrite_num);
    dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
    if dxl_comm_result ~= COMM_SUCCESS
        fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
    end

    % Clear syncwrite parameter storage
    groupSyncWriteClearParam(groupwrite_num);

    while 1
        % Syncread present position
        groupSyncReadTxRxPacket(groupread_num);
        dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
        if dxl_comm_result ~= COMM_SUCCESS
            fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
        end

        % Check if groupsyncread data of Dynamixel#1 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL1_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end

        % Check if groupsyncread data of Dynamixel#2 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL2_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end

         % Check if groupsyncread data of Dynamixel#3 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL3_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end

        % Check if groupsyncread data of Dynamixel#4 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL4_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end
        
         % Check if groupsyncread data of Dynamixel#5 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL5_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end
        
         % Check if groupsyncread data of Dynamixel#6 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL6_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end

        % Check if groupsyncread data of Dynamixel#7 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL7_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end

         % Check if groupsyncread data of Dynamixel#8 is available
        dxl_getdata_result = groupSyncReadIsAvailable(groupread_num, DXL8_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);
        if dxl_getdata_result ~= true
          fprintf('[ID:%03d] groupSyncRead getdata failed', DXL1_ID);
          return;
        end
        
        % Get Dynamixel#1 present position value
        dxl_present_position1 = groupSyncReadGetData(groupread_num, DXL1_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

        % Get Dynamixel#2 present position value
        dxl_present_position2 = groupSyncReadGetData(groupread_num, DXL2_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

        
        % Get Dynamixel#3 present position value
        dxl_present_position3 = groupSyncReadGetData(groupread_num, DXL3_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

        % Get Dynamixel#4 present position value
        dxl_present_position4 = groupSyncReadGetData(groupread_num, DXL4_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

        % Get Dynamixel#5 present position value
        dxl_present_position5 = groupSyncReadGetData(groupread_num, DXL5_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

         % Get Dynamixel#6 present position value
        dxl_present_position6 = groupSyncReadGetData(groupread_num, DXL6_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

        % Get Dynamixel#7 present position value
        dxl_present_position7 = groupSyncReadGetData(groupread_num, DXL7_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

        
        % Get Dynamixel#8 present position value
        dxl_present_position8 = groupSyncReadGetData(groupread_num, DXL8_ID, ADDR_PRO_PRESENT_POSITION, LEN_PRO_PRESENT_POSITION);

        fprintf('[ID:%03d] GoalPos:%03d  PresPos:%03d\t[ID:%03d] GoalPos:%03d  PresPos:%03d\t[ID:%03d] GoalPos:%03d  PresPos:%03d\t[ID:%03d] GoalPos:%03d  PresPos:%03d\t[ID:%03d] GoalPos:%03d  PresPos:%03d\t[ID:%03d] GoalPos:%03d  PresPos:%03d\t[ID:%03d] GoalPos:%03d  PresPos:%03d\t[ID:%03d] GoalPos:%03d  PresPos:%03d\n', DXL1_ID, dxl_goal_position1(index), typecast(uint32(dxl_present_position1), 'int32'), DXL2_ID, dxl_goal_position2(index), typecast(uint32(dxl_present_position2), 'int32'), DXL3_ID, dxl_goal_position3(index), typecast(uint32(dxl_present_position3), 'int32'),DXL4_ID, dxl_goal_position4(index), typecast(uint32(dxl_present_position4), 'int32'), DXL5_ID, dxl_goal_position5(index), typecast(uint32(dxl_present_position5), 'int32'), DXL6_ID, dxl_goal_position6(index), typecast(uint32(dxl_present_position6), 'int32'), DXL7_ID, dxl_goal_position7(index), typecast(uint32(dxl_present_position7), 'int32'), DXL8_ID, dxl_goal_position8(index), typecast(uint32(dxl_present_position8), 'int32'));


        if ~((abs(dxl_goal_position1(index) - typecast(uint32(dxl_present_position1), 'int32')) > DXL_MOVING_STATUS_THRESHOLD) || (abs(dxl_goal_position2(index) - typecast(uint32(dxl_present_position2), 'int32')) > DXL_MOVING_STATUS_THRESHOLD) || (abs(dxl_goal_position3(index) - typecast(uint32(dxl_present_position3), 'int32')) > DXL_MOVING_STATUS_THRESHOLD) || (abs(dxl_goal_position4(index) - typecast(uint32(dxl_present_position4), 'int32')) > DXL_MOVING_STATUS_THRESHOLD) || (abs(dxl_goal_position5(index) - typecast(uint32(dxl_present_position5), 'int32')) > DXL_MOVING_STATUS_THRESHOLD) ||(abs(dxl_goal_position6(index) - typecast(uint32(dxl_present_position6), 'int32')) > DXL_MOVING_STATUS_THRESHOLD) || (abs(dxl_goal_position7(index) - typecast(uint32(dxl_present_position7), 'int32')) > DXL_MOVING_STATUS_THRESHOLD) || (abs(dxl_goal_position8(index) - typecast(uint32(dxl_present_position8), 'int32')) > DXL_MOVING_STATUS_THRESHOLD))
            
            
            break;
        end
    end
    
    k1=dxl_present_position1;
    k2=dxl_present_position2;
    k3=dxl_present_position3;
    k4=dxl_present_position4;
    k5=dxl_present_position5;
    k6=dxl_present_position6;
    k7=dxl_present_position7;
    k8=dxl_present_position8;
    
    theta1=(k1*181/200000)-2000;
    theta2=(k2*181/200000)-2000;
    theta3=(k3*181/200000)-2000;
    theta4=(k4*181/200000)-2000;
    theta5=(k4*181/200000)-2000;
    theta6=(k6*181/200000)-2000;
    theta7=(k7*181/200000)-2000;
    theta8=(k8*181/200000)-2000;
    
    py2=46/2000*sin(theta1)+l*sin(theta2)+l*sin(theta3)+l*sin(theta4)+l*sin(theta5)+l*sin(theta6)+l*sin(theta7)+l*sin(theta8);
    px2=46/2000*cos(theta1)+l*cos(theta2)+l*cos(theta3)+l*cos(theta4)+l*cos(theta5)+l*cos(theta6)+l*cos(theta7)+l*cos(theta8);
 E1=J1-k1;
 E2=J2-k2;
 E3=J3-k3;
 E4=J4-k4;
 E5=J5-k5;
 E6=J6-k6;
 E7=J7-k7;
 E8=J8-k8;  
    
   end
  J(1)=2000; J(2)=2000; J(3)=2000; J(4)=2000; J(5)=0; J(6)=2000; J(7)=2000; J(8)=0; 
end


% Disable Dynamixel#1 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL1_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_DISABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
end

% Disable Dynamixel#2 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL2_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_DISABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
end

% Disable Dynamixel#3 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL3_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_DISABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
end

% Disable Dynamixel#4 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL4_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_DISABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
end

% Disable Dynamixel#5 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL5_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_DISABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
end

% Disable Dynamixel#6 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL6_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_DISABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
end

% Disable Dynamixel#7 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL7_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_DISABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
end
% Disable Dynamixel#8 Torque
write1ByteTxRx(port_num, PROTOCOL_VERSION, DXL8_ID, ADDR_PRO_TORQUE_ENABLE, TORQUE_DISABLE);
dxl_comm_result = getLastTxRxResult(port_num, PROTOCOL_VERSION);
dxl_error = getLastRxPacketError(port_num, PROTOCOL_VERSION);
if dxl_comm_result ~= COMM_SUCCESS
    fprintf('%s\n', getTxRxResult(PROTOCOL_VERSION, dxl_comm_result));
elseif dxl_error ~= 0
    fprintf('%s\n', getRxPacketError(PROTOCOL_VERSION, dxl_error));
end
% Close port
closePort(port_num);

% Unload Library
unloadlibrary(lib_name);

close all;
clear all;

**Comment by ROBOTIS-Will** [comment]
This issue thread will be closed as there isn't recent activity. Please feel free to reopen when necessary.
