### ISSUE TITLE
unable to install dynamixel sdk

### ISSUE THREAD

**Issue by aswinkumar2019** [ROBOTIS-GIT/DynamixelSDK#328]
root@aswin-desktop:~/Drivers/DynamixelSDK/c++/build/linux64# make
mkdir -p ./.objects/
g++ -O2 -O3 -DLINUX -D_GNU_SOURCE -Wall -c -I../../include/dynamixel_sdk -m64 -fPIC -g -c ../../src/dynamixel_sdk/group_bulk_read.cpp -o .objects/group_bulk_read.o
g++: error: unrecognized command line option ‘-m64’
Makefile:117: recipe for target '.objects/group_bulk_read.o' failed
make: *** [.objects/group_bulk_read.o] Error 1

Please help me to fix this error

**Comment by aswinkumar2019** [comment]
Is the project active????

**Comment by ROBOTIS-zerom** [comment]
Hello,

Make sure you are using a 64-bit OS.
Perhaps your g++ compiler is for 32bit only.

**Comment by aswinkumar2019** [comment]
sorry,i think i checkedout kinetic-devel while installing ros melodic.I think this may be the reason for the issue.I shall check it out and update response here

**Comment by aswinkumar2019** [comment]
I dont think these two are the issues,i have 64bit OS

**Comment by ROBOTIS-zerom** [comment]
A simple way to solve the problem is to simply remove the -m64 flag.

Are you sure you have an x86_64 processor?
Because -m64 is only valid for x86_64 processors..
It cannot be used on processors like arm64.

**Comment by aswinkumar2019** [comment]
Sorry, I have jetson nano which is based on arm64. I am not sure.
I can't use dynamixel sdk with jetson nano or arm64 devices????

**Comment by ROBOTIS-zerom** [comment]
No.. you just remove the -m64 flag in the Makefile.

Change below line
```
FORMAT     = -m64
```
to..
```
FORMAT     =
```

**Comment by aswinkumar2019** [comment]
It works perfectly, thank you very much
