### ISSUE TITLE
[3.7.0][C][C#][C++][LN-101][XL-320] Issue : Compile errors in all platforms

### ISSUE THREAD

**Issue by uwouldknow** [ROBOTIS-GIT/DynamixelSDK#329]
This is what I am using:
Windows 10
DynamixelSDK version 3.7.0
Visual Studio 2019
[C] / [C++] / [C#]
xl-320
opencm9.04
LN-101

Here is my issue:

Hello I am trying to get the SDK to work with c# so I can use it with unity but I am running into errors.... Firstly as soon as I open the C# solution "protocol_combined.sln" I recieve these errors shown below..... 

![csharp2](https://user-images.githubusercontent.com/53582885/62326707-9967f600-b463-11e9-9c89-05c25e8e0521.JPG)

I was able to change to code so that it would at least compile as shown below......

![csharp1](https://user-images.githubusercontent.com/53582885/62326759-b69cc480-b463-11e9-8d5d-9b8fdc7570d4.JPG)

After this I ran the code and received this error shown below......

![csharp3](https://user-images.githubusercontent.com/53582885/62326792-d0d6a280-b463-11e9-8649-9afa407a86d4.JPG)

Next I tried getting C and C++ to work but ran into issues as well.... with both languages I ran into the same error when running the "protocol_combined.sln" that is shown below....

![Capture](https://user-images.githubusercontent.com/53582885/62326875-f9f73300-b463-11e9-86a9-f23f88f1b837.JPG)

Also am I supposed to be doing something special when the option in the picture below shows up?

![upgrade](https://user-images.githubusercontent.com/53582885/62326911-15fad480-b464-11e9-8b75-1f73b5209d5b.JPG)

Furthermore do I have to use Visual Studios 2015 or can I use the new version of Visual Studios and if I use the new version I would have to change that setting in the picture below right? Same question with the WindowsSDK version as well

![version](https://user-images.githubusercontent.com/53582885/62326981-42aeec00-b464-11e9-9a19-5854cae8ebb2.jpg)

And yes I followed all of the steps from this website http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/overview/#dynamixel-sdk

Overall I just want it to work in c# but I thought I should mention my issues with c and c++ as well.

**Comment by colejbutler** [comment]
Update: I recently tried with visual studio 2015 express and received the same error

**Comment by ROBOTIS-zerom** [comment]
OK. I found a bug in the code.
I will fix the bug and upload it, and notify you again.

**Comment by ROBOTIS-zerom** [comment]
I fixed the bug. Check out the latest master branch..

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
