### ISSUE TITLE
Bug in XM430 firmware ?

### ISSUE THREAD

**Issue by jacqu** [ROBOTIS-GIT/DynamixelSDK#33]
Hi,

When using a XM430 in extended position mode, reading present position (register address 132) gives -4096 where position should be -1. Adjacent values are ok (0 and -2).

Position value / Bytes given by a bulk read command
0 -> 0 0 0 0
-1 -> 0 240 255 255 (should be 255 255 255 255)
-2  -> 254 255 255 255

Maybe I missed something. Thanks for helping.
Jacques

**Comment by jacqu** [comment]
This is a workaround that seems to work (the Simulink block communicates with a XM430). The glitch happens every multiple of 4096.

![capture d ecran 2016-09-23 a 13 27 12](https://cloud.githubusercontent.com/assets/5345039/18784305/8281e138-8191-11e6-9e85-9d2f8ac00e26.png)

**Comment by jacqu** [comment]
I just discovered that it is possible to upgrade the firmware with the R+ manager 2.0. The glitch disappeared in the latest firmware.

Sorry for the noise. You can close the issue.

**Comment by ROBOTIS-Leon** [comment]
You did great!

Anyway, the issue which is related with the hardwares including Dynamixels and its firmwares, and stuffs, would be glad if you ask support@robotis.com for next time. :)
