### ISSUE TITLE
[3.7.0][C++][USB2Dynamixel2][MX-12W] Issue : Read speed of read2byteTxRx

### ISSUE THREAD

**Issue by poornapragnarao** [ROBOTIS-GIT/DynamixelSDK#330]
I'm using `DynamixelSDK ver. 3.7.0`

I'm using `C++ Language`

I'm using `USB2Dynamixel2 `serial converter

I'm using `MX-12W`

and I'm having an issue:

read2ByteTxRx takes about 15ms to return. Is this expected? 
Further information - 
Hardware:
1. Raspberry pi 3 B+
Software:
1. Return delay time is set to minimum
2. Baud Rate is 1000000

**Comment by sigma--** [comment]
Same execution time in Windows 10

**Comment by ROBOTIS-zerom** [comment]
Have you tried changing the usb latency timer value?
The default value of the latency timer is 16ms. Change this value to 1ms and try again.

http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#usb-latency-setting

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
