### ISSUE TITLE
Pro series firmware upgrade to PRO(A)

### ISSUE THREAD

**Issue by AaronZhu2018** [ROBOTIS-GIT/DynamixelSDK#346]
Based on this topic
https://community.robotsource.org/t/introduction-of-dynamixel-pro/1424

http://emanual.robotis.com/docs/en/dxl/pro/
So, Can I upgrade my H54-200-S500-R to H54-200-S500-R(A)

Because I want to control the velocity profile!

Thanks in advance!

**Comment by ROBOTIS-zerom** [comment]
Hello, Aaron.
Yes, you can change the firmware by just recovering it with (A) firmware.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
