### ISSUE TITLE
[3.7.11][C][USB2Dynamixel2][mx-64] Issue : groupSyncRead getdata failed in Protocol 2

### ISSUE THREAD

**Issue by ryans799** [ROBOTIS-GIT/DynamixelSDK#354]
- I'm using `DynamixelSDK ver. 3.7.11`
- I'm using `C` Language
- I'm using `USB2Dynamixel2` serial converter
- I'm using `MX-64
- and I'm having an `issue` : groupSyncRead getdata failed while I tried example sync_read_write "$~/DynamixelSDK-3.7.11/c/example/protocol2.0/sync_read_write/linux64" in Protocol 2.0.
![Screenshot from 2019-10-25 00-28-24](https://user-images.githubusercontent.com/32617854/67510011-66c64600-f6be-11e9-91f8-08c54f382b9b.png)

**Comment by ryans799** [comment]
![Screenshot from 2019-10-25 15-40-28](https://user-images.githubusercontent.com/32617854/67556687-cb74b580-f73d-11e9-8221-8e69563d19d9.png)
that is my parameter, i changed the parameter address from dynamixel PRO (default example protocol 2) into parameter mx 64 in protocol 2.

**Comment by ryans799** [comment]
Actually I tried sync_read_write in Protocol 1, it's success. but when I tried sync_read_write in protocol 2, it failed and shown "groupSyncRead getdata failed".

I have 4 dynamixels mx-64.
I chekced sync_read_write with 2 dynamixels MX64(firmware version=39) for protocol 1.
I chekced sync_read_write with 2 dynamixels MX64(firmware version=43) for protocol 2.

**Comment by ROBOTIS-zerom** [comment]
Hi, ryans
In MX-64(2.0), the Goal Position and the Present Position are 2 bytes.
Modify the length values for lines 47, 48 from 4 to 2.

**Comment by ryans799** [comment]
I have modified the length values for lines 47, 48 from 4 to 2
![Screenshot from 2019-10-29 11-21-35](https://user-images.githubusercontent.com/32617854/67737703-d9c51900-fa3e-11e9-8bbd-08b88368bf0d.png)

but the motor didn't work well. the instruction couldn't write the motor 
![Screenshot from 2019-10-25 00-28-24](https://user-images.githubusercontent.com/32617854/67737801-0e38d500-fa3f-11e9-88cf-d93f6b8210f5.png)

**Comment by ROBOTIS-zerom** [comment]
I'm sorry. I made a mistake looking at the MX-64 Control Table.
The Goal Position and Present Position of the MX-64(2.0) are 4 bytes. 

I have no problem with it.

![image](https://user-images.githubusercontent.com/15886081/67744620-61258300-fa65-11e9-8bbc-19601f1be79c.png)

![image](https://user-images.githubusercontent.com/15886081/67744656-7bf7f780-fa65-11e9-907d-2fbd33be0034.png)

**Comment by ryans799** [comment]
can I ask the source code which you used? I'll try it with my dynamixel mx-64(2.0)

**Comment by ROBOTIS-zerom** [comment]
The part I changed in the master branch is the capture image above.
Only six lines. 

See the attachment here:
[sync_read_write.zip](https://github.com/ROBOTIS-GIT/DynamixelSDK/files/3807763/sync_read_write.zip)

**Comment by ryans799** [comment]
where is "#define LEN_PRO_PRESENT_POSITION" in your code?
in my code, there is "#define LEN_PRO_PRESENT_POSITION" in line 48.
is "#define LEN_PRO_PRESENT_POSITION" omitted?

**Comment by ROBOTIS-zerom** [comment]
In the attachment, the code is in line 48.

**Comment by ryans799** [comment]
I have tried again with your code. but the result is just the same as me. "groupSyncRead getdata failed".
![Screenshot from 2019-11-06 08-32-34](https://user-images.githubusercontent.com/32617854/68196290-f509c880-ffea-11e9-846d-176fc578a653.png)
sometimes it's success, and sometimes it's failed. I don't know why it happens. and I don't have any solution to repair this bug.

**Comment by ROBOTIS-Will** [comment]
This issue thread will be closed as there isn't recent activity. Please feel free to reopen when necessary.
