### ISSUE TITLE
Error when changing operating mode

### ISSUE THREAD

**Issue by radufb** [ROBOTIS-GIT/DynamixelSDK#355]
Hi,

I am having trouble changing the operating mode of a Dynamixel MX-64. The read_write.cpp file works fine and the motor is rotating back and forth but i want to control it using PWM values.

I thus try to change operating mode (i use protocol 2.0) by using the following code:

#define ADDR_OPERATING_MODE                  11
#define DXL_OPERATING_MODE_VALUE        16
.
.
.
.
dxl_comm_result = packetHandler->write1ByteTxRx(portHandler, DXL_ID, ADDR_OPERATING_MODE, DXL_OPERATING_MODE_VALUE, &dxl_error);
  if (dxl_comm_result != COMM_SUCCESS)
  {
    printf("%s\n", packetHandler->getTxRxResult(dxl_comm_result));
  }
  else if (dxl_error != 0)
  {
    printf("%s\n", packetHandler->getRxPacketError(dxl_error));
  }
  else
  {
    printf("Operating Mode changed to PWM Mode\n");
  }

But i get the following error: [RxPacketError] Writing or Reading is not available to target address!
According to the datashet it should be a valid address and value for the PWM operating mode...

Any ideas for why it won't allow me to change operating mode?

**Comment by ROBOTIS-zerom** [comment]
Hi,
Did you recover with the MX-64(A) firmware?
If so, the address is in ROM area. So if you write with torque on, the write will fail.

Check the firmware with R+ Manager 2.0 or DYNAMIXEL Wizard 2.0
It should be recognized as MX-64(A), not MX-64.
And make sure the device's torque is off before testing.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
