### ISSUE TITLE
OpenCM 9.04+ EXP Board + R+Task 2.0+: Hardware power switch addition

### ISSUE THREAD

**Issue by kkk123m** [ROBOTIS-GIT/DynamixelSDK#360]
STEP 1. Check what you are suffering from :

- I'm using `R+ task 2.0`

  - I am using  [OpenCM904] 

- I'm using `XL430-W210-R`

 - and I'm having an `issue` to add additional hardware power switch
  STEP 2. Write `Title` as `[3.5.4][C++][USB2Dynamixel2][XM430-W210-R] Issue : My motor doesn't work`

STEP 3. Delete all written here, and describe what your problem is

Hi, I am trying to add additional external power On/Off switch to power supply to start and stop Dynamixel by user. What is the best method for that, should I use external Digital On off switch connected as sensor to OpenCm 9.04 or is there any simple better on off switch can be inserted between power supply and OpenCM 9.04_ EXP board. Please let me know. 

Thanks

**Comment by ROBOTIS-zerom** [comment]
Hi, kkk123m.
This is not an issue with the Dynamixel SDK.

What is the purpose of adding an external power On/Off switch?
If you want to turn the Dynamixel's torque on and off, you can set "Torque Enable" 0 / 1 in the Control Table without adding a switch. 

http://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#torque-enable

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
