### ISSUE TITLE
[3.7.21][Python][USB2Dynamixel2][AX-12A] Issue : My motors are not detected

### ISSUE THREAD

**Issue by jfgauron** [ROBOTIS-GIT/DynamixelSDK#367]
Hi, I have 8 dynamixels that are connected together. Everything worked fine until I changed all their ids to 200,201,202, ... Now, none of my motors are detected. I tried testing one motor at a time and I have the same results for all motors.

I tried running `factory_reset.py` (in `python/tests/protocol1_0`) and the script returned:

> Succeeded to open the port
> Succeeded to change the baudrate
> Now the controller baudrate is : 1000000
> [ID:001] Try factoryreset : 
> Aborted
> [TxRxResult] There is no status packet!
 
Any idea why, and how I can fix this? Thank you.

**Comment by ROBOTIS-zerom** [comment]
Hi,
AX-12 does not support "Factory Reset" instruction.
Check below link:
http://emanual.robotis.com/docs/en/dxl/protocol1/#factory-reset

Applied Products : MX-12W(V41), MX-28(V40), MX-64(V40), MX-106(V40), X-series(except XL-320), MX series with Protocol 2.0

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
