### ISSUE TITLE
[3.5.4][Arduino][OpenCM904+485EXP][XM540-W270-R] Writing acceleration, velocity and position in one packet

### ISSUE THREAD

**Issue by ercknz** [ROBOTIS-GIT/DynamixelSDK#373]
I am working a a force controlled robot and have not been able to find a way to write accelerations, velocities, and positions. Currently I have my robot running in position control and it works by sync writing positions but i would like to control more about each movement. Is there a different mode or function I should be using? Is there a way to at least write position and velocity in one packet? Or is it position OR velocity depending on the mode only.

**Comment by ROBOTIS-zerom** [comment]
We recommended that you read the manual first.
http://emanual.robotis.com/docs/en/dxl/x/xm540-w270/

XM540 Operating Mode : http://emanual.robotis.com/docs/en/dxl/x/xm540-w270/#operating-mode

If you want to write the acceleration, velocity and position values in one packet, you can also use sync write instruction.
http://emanual.robotis.com/docs/en/dxl/protocol2/#sync-write

The profile acceleration address is 108 and the length is 4 bytes.
The profile velocity address is 112 and the length is 4 bytes.
The goal position address is 116 and the length is 4 bytes.

So, you can write a 12 bytes from address 108 using syncwrite instruction.
![image](https://user-images.githubusercontent.com/15886081/73519440-759e6080-4444-11ea-8623-6e151d2d88f0.png)
starting address : 108
data length : 12

**Comment by ercknz** [comment]
Oh I see. I think my issue was that I was feeding velocities to the velocity profile without changing it from time-based profile. Thank you.
