### ISSUE TITLE
How to change Dynamixel firmware version

### ISSUE THREAD

**Issue by ryans799** [ROBOTIS-GIT/DynamixelSDK#384]
Hi, 
I have upgraded my dynamixel MX-64 firmware version into V.43.
I thing this will be okay, but I'am actually dissapointed. because this version doesn't support Protocol 1, only support Protocol 2.
How to downgrade that firmware version? so I can use protocol 1 in my dynamixel.

my previous firmware version is V.39.

**Comment by ROBOTIS-zerom** [comment]
Hi, ryans.
You just recover the firmware with "MX-64" firmware. ( NOT "MX-64(2.0)" firmware. )
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#firmware-recovery

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
