### ISSUE TITLE
[3.5.4][C++][USB2Dynamixel2][MX-64-AR] Issue : Simultaneous goal position and velocity control - which mode?

### ISSUE THREAD

**Issue by cmheunis** [ROBOTIS-GIT/DynamixelSDK#387]
Hi there,
I'm using DynamixelSDK ver. 3.5.4, C++ Language
And I am trying to assign both a goal position and goal velocity using indirect addresses as explained by [the manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/cpp_indirect_address_protocol_2_0/#cpp-indirect-address-protocol-20).
**I am not sure if I should set the operating mode to velocity control or not.** 
I want to control 6 motors simultaneously by sending a goal position - but different speeds for each motor. 

Thanks in advance.

**Comment by ROBOTIS-zerom** [comment]
Hi, 
First of all, are you using Protocol 2.0 Firmware?
The position cannot be controlled in the velocity control mode.
If you want to control both position and velocity, you should use the goal position and profile velocity value. 
http://emanual.robotis.com/docs/kr/dxl/mx/mx-64-2/#profile-velocity 

In position control mode, goal velocity value is not used.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
