### ISSUE TITLE
Setting the unique ID of each actuator

### ISSUE THREAD

**Issue by abencomo** [ROBOTIS-GIT/DynamixelSDK#39]
Does the DynamixelSDK have a function that allows to set  the unique ID of each actuator or do I need to use DYNAMIXEL Wizard for that?

**Comment by ROBOTIS-Leon** [comment]
Hi,

Could you tell me more about what 'Unique ID' is?

The following are what I guessed.

1. Theres no any specific function that changes ID is not in the DynamixelSDK.

2. 'I want to set the ID by myself anyway' : 
  visit [support.robotis.com/en](support.robotis.com/en) and see the control table your Dynamixel has.
  Find the address of ID, and change its ID by write1ByteTx() or write1ByteTxRx();

3. If you are a ROS user, try using [Dynamixel Workbench](https://github.com/ROBOTIS-GIT/dynamixel-workbench) that supports you with GUI environment.

4. 'I want to set the ID to 0 or over 255':
You can just change it by following step 2., but it wouldn't work.

**Comment by abencomo** [comment]
Hi Leon,

Answer 2 is what I was looking for.  I'd like to change the ID of each servo programmatically instead of using the DYNAMIXEL Wizard. Thanks!

<img width="478" alt="screen shot 2016-11-07 at 10 39 04 pm" src="https://cloud.githubusercontent.com/assets/7515273/20089446/e73f57fe-a53b-11e6-9cea-89205a0cda6b.png">

**Comment by abencomo** [comment]
Leon,

How can I persist/apply the changes to address 25 (LED)?  I keep changing it via the DYNAMIXEL Wizard, but I after I power down and power up the servo again, the LED is Off (value is 0).

<img width="503" alt="screen shot 2016-11-07 at 10 40 11 pm" src="https://cloud.githubusercontent.com/assets/7515273/20089582/c29978d4-a53c-11e6-88a6-4d32a8d8ecbf.png">

**Comment by ROBOTIS-Leon** [comment]
Hi,
I hope you might become able to change the ID :)

the Torque Enable and LED value would be initialized to 0 automatically, when you shut its power down.

Note that those so-called Items placed in the RAM can't be kept its data when the power is gone.
Only the red stuffs shown in previous picture will be kept permanently.
