### ISSUE TITLE
[C++, Python][U2D2][XM540-W270-T] Issue: problems using read_write test file

### ISSUE THREAD

**Issue by db4207** [ROBOTIS-GIT/DynamixelSDK#391]
Hi everyone, I’m new to programming: I’m a mechanical engineer in school currently. I’m having to create a robotic arm for my internship and I’m using the Dynamixel XM540-W270-T and XM430-W350-T servos. I can get the servos to move using the Dynamixel Wizard, but I’m trying to test them with the read_write.py code in PyCharm. I’ve also tried testing the C++ code in Visual Studio 2015. I’m having two different errors I don’t know how to solve. In PyCharm I get this error:

![image](https://user-images.githubusercontent.com/63661738/79253311-fae4bf00-7e50-11ea-87ff-1ab41d283ba2.png)

And in Visual Studio I run the code and it continually posts this:

![image](https://user-images.githubusercontent.com/63661738/79253341-06d08100-7e51-11ea-8864-25a8216a746c.png)

Can anyone provide any input? I’m completely lost. Sorry for my lack of background with programming.

**Comment by ROBOTIS-zerom** [comment]
Hi, 
In Python, Did you building and setup the library?
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/python_windows/#building-the-library

In C++, You ran the read_write example of Protocol 1.0.
However, MX-series Dynamixel uses Protocol 2.0. 
Try using the Protocol 2.0 example.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
