### ISSUE TITLE
[3.7.21][C++][USB2Dynamixel2][PM42][MX-64] Issue: I am unable to control both motors with bulk_read_write

### ISSUE THREAD

**Issue by levin-b** [ROBOTIS-GIT/DynamixelSDK#393]
I updated the MX-64 to run Protocol 2.0 so that both motors use the same protocol. 

I modified the bulk_read_write code to store the correct memory addresses for both the PM-42 and the MX-64. I was able to bulk_read_write to 2 MX-64 at the same time but I was unable to add the PM-42 to the bulk_read_write.

After running the program, I get this read-out:

`Succeeded to open the port!
Succeeded to change the baudrate!
Dynamixel#1 has been successfully connected 
Dynamixel#2 has been successfully connected 
Dynamixel#3 has been successfully connected 
Press any key to continue! (or press ESC to quit!)
[TxRxResult] There is no status packet!
[ID:001] groupBulkRead getdata failed
`

What could be causing this problem?

When using the addParam method I make sure that the right motor_id are matched with the correct addresses, byte length, and param_goal_position.

I am aware that the 2 motor series have different position scopes so I created 1 set of param goal positions for the pro motors and another set for the MX-64s.

Thank you for your help.

**Comment by ROBOTIS-zerom** [comment]
I don't think there is enough information.

It is difficult for us to debug your code. 
Moreover, it is impossible to find a bug by simply explaining your code.

If it doesn't work, the wrong code might have been used somewhere, but you say you used it all correctly, so I can't find the problem.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
