### ISSUE TITLE
[3.7.2][C++][OpenCR][XL430-W250-T]: What's the correct way to sync goal velocity of two dynamixel's to make my robot drive straight ?

### ISSUE THREAD

**Issue by Vinz1911** [ROBOTIS-GIT/DynamixelSDK#394]
Hello,

My name is Vinz and first I would like to say: great work with the DynamixelSDK, it's very nice to control my Dynamixel XL430 with it. I'm using the latest version of DynamixelSDK on my Turtlebot3. I using direct communication without ROS2. My OpenCR uses USBtoDynamixel Firmware, so that I can directly use the DynamixelSDK.

So I'm currently working on a remote control for my turtlebot and i discovered that my turtlebot is not driving straight. I'm using C++ and the group bulk write option. My Dynamixels are in Velocity Control Mode. 

So I'm not sure if this is the correct way but I would like to know how is the best way to let two dynamixels work perfectly synced to make my turtlebot drive in a straight line.

Thank you and best regards,
Vinz

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
