### ISSUE TITLE
Using the BulkRead function with the AX series

### ISSUE THREAD

**Issue by abencomo** [ROBOTIS-GIT/DynamixelSDK#40]
According to this [documentation](https://github.com/ROBOTIS-GIT/DynamixelSDK/wiki/2.2-Dynamixel), the BulkRead function doesn't work with the AX series.  Is that still the case today and why?

How about the BulkWrite function?  Will that work with the the AX series?

**Comment by ROBOTIS-Leon** [comment]
The bulkwrite only works in Protocol 2.0.
The AX series works with Protocol 1.0,
so you cant use that function with AX.

That lasts still today, and to know the scheduled future works for Dynamixel, try having a contact with contactus2@robotis.com

Thank you for the interest
