### ISSUE TITLE
how to use DynamixelSDK with ROS ?

### ISSUE THREAD

**Issue by vikishaw** [ROBOTIS-GIT/DynamixelSDK#42]
I want us ros to control dynamixel. How should i do

**Comment by ROBOTIS-Leon** [comment]
the [Dynamixel Workbench](http://wiki.ros.org/dynamixel_workbench) would help you understand the way to use. :)

**Comment by vikishaw** [comment]
Thanks for your reply. However, My ROS version is indigo. The Dynamixel Workbench only supports kinetic.So can they be integrated.

**Comment by routiful** [comment]
Hi, vikishaw 

I checked the [Dynamixel-Workbench](http://wiki.ros.org/dynamixel_workbench) is worked well in Indigo version.
But, you need to clone it to your catkin workspace.

Thanks.
