### ISSUE TITLE
DynamixelSDK-341 dxl_x86_c COM Port Handling

### ISSUE THREAD

**Issue by CLS-kyleth** [ROBOTIS-GIT/DynamixelSDK#43]
Implemented the dxl_x86_c.dll driver on a 64-bit Windows 7 OS.

Was able to use the Roboplus Dynamixel Manager software to control my USB2Dynamixel,

Was NOT able to open communication using the dxl_x86_c.dll.

The issue was resolved by setting the USB2Dynamixel adapter COM Port number in Windows to a single digit address (e.g. COM12 DID NOT work, but COM9 DID work).

Please look into this to determine the root cause for future applications.

Thank you.

**Comment by ROBOTIS-Leon** [comment]
Hi,

Thank you for your pointing.

The issue you've told is already improved, so you can use your port with the number over 10 now
by using the source uploaded into the develop branch of GITHUB.

You can get those sources directly by downloading or change the branch to the through like the Git Bash. :)
