### ISSUE TITLE
port conneting problem

### ISSUE THREAD

**Issue by shyeonaaa** [ROBOTIS-GIT/DynamixelSDK#45]
Hello! It's good material. thank you for making it.

anyway I'm using MATLAB R2016a on windows 10 and using Dynamixel MX-28.

I have a problem that failed to open the port with matlab.

whenever I run this program, it doesn't work with "Failed to open the port!"

however the dynamixel is normally connected to Dynamixel Wizard Roboplus.

also, I checked the comport number and edited it on mfile(read_write.m) of protocol1.0. 

I want know why it doesn't work.

if you let me know, I will really appreciate it.

**Comment by ROBOTIS-Leon** [comment]
Hi, 

Sorry for the inconvenience.

Would you check if your com port number is over 10?

**Comment by shyeonaaa** [comment]
Hello!

My com port number is 10. Is it any problem?



2017년 1월 11일 (수) 오후 8:43, Leon <notifications@github.com>님이 작성:

**Comment by ROBOTIS-Leon** [comment]
Ok, let's try to change the com port number to under then 10 through the device manager -> select the com port which points out your USB device , then go properties -> port settings -> advanced settings -> select another com port number, then click ok.

It must be worked well.
