### ISSUE TITLE
Strange Control Table Address

### ISSUE THREAD

**Issue by CodePed** [ROBOTIS-GIT/DynamixelSDK#456]
I just tested read_write.cpp in C++ linux64 example code. In line 42, 43 and 44 where you define the control table address, the example code define them as 562, 596 and 611.And when I run the code, it will show 
"[RxPacketError] The data value is out of range!"
![Screenshot from 2020-10-28 16-47-56](https://user-images.githubusercontent.com/45098447/97414281-c0e79000-193e-11eb-8281-0a676673cfb9.png)
So I checked the control table on your website:https://emanual.robotis.com/docs/en/dxl/mx/mx-28-2/#control-table
The correct address should be 64, 116 and 132. If you run the code with default ADDR_PRO_GOAL_POSITION and ADDR_PRO_PRESENT_POSITION, it will show 
"[RxPacketError] The data length does not match as expected!"
![Screenshot from 2020-10-28 16-58-44](https://user-images.githubusercontent.com/45098447/97414406-ea082080-193e-11eb-8f57-abec07752eb4.png)
So I replace all of them with the address you've provided on the website, and everything is correct now.
![Screenshot from 2020-10-28 16-58-54](https://user-images.githubusercontent.com/45098447/97414433-f0969800-193e-11eb-95b3-e585512735ae.png)
I wondered why the default addresses are like that big, the comment said they are different in dynamixel mode. What does that mean?

**Comment by ROBOTIS-Will** [comment]
Closing this thread as there isn't recent activity. Please feel free to reopen when necessary.
