### ISSUE TITLE
The DYNAMIXEL XL430-W250-T does not respond to the read and ping instruction.

### ISSUE THREAD

**Issue by dvlprjrlvno** [ROBOTIS-GIT/DynamixelSDK#459]
Hi, i've been trying to read the present position or the ping instruction of the DYNAMIXEL XL430-W250-T, but I have not been able to read the current position of the servo. The servo does not respond to the read instruction.

There is some register that needs to be configured to activate the read operation?

Currently I can successfully execute write operations on the EEPROM. 

I am executing this instruction in arduino due to read the present position:

0xFF | 0xFF | 0xFD | 0x00 | 0x01 | 0x07 | 0x00 | 0x02 | 0x84 | 0x00 | 0x04 | 0x00 | 0x1D | 0x15

Thanks.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as identical inquiry in #306
