### ISSUE TITLE
unable to make dynamixel SDK

### ISSUE THREAD

**Issue by bakwankawa** [ROBOTIS-GIT/DynamixelSDK#476]
alfa@alfa:~/alfarobi/src/DynamixelSDK/c++/example/dxl_monitor/linux64$ make

mkdir -p .objects/
g++ -O2 -O3 -DLINUX -D_GNU_SOURCE -Wall -I../../../include/dynamixel_sdk -m64 -g  .objects/dxl_monitor.o -o dxl_monitor -ldxl_x64_cpp -lrt
/usr/bin/ld: cannot find -ldxl_x64_cpp
collect2: error: ld returned 1 exit status
Makefile:62: recipe for target 'dxl_monitor' failed
make: *** [dxl_monitor] Error 1

please help me fix this error, thanks!

**Comment by ROBOTIS-Will** [comment]
hi @bakwankawa 
In order to run the example, you need to build and install the c++ library first as described below.
https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/cpp_linux/#cpp-linux
Thanks!

**Comment by bakwankawa** [comment]
> hi @bakwankawa
> In order to run the example, you need to build and install the c++ library first as described below.
> https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/cpp_linux/#cpp-linux
> Thanks!

Thanks for the solutions, work great!
