### ISSUE TITLE
printRxPacketError

### ISSUE THREAD

**Issue by Delet0r** [ROBOTIS-GIT/DynamixelSDK#48]
Greetings,

it is not really an issue but I just wanted to mention, that in the API documentation printRXPacketError is not documented.

Sincerly Delet0r

**Comment by ROBOTIS-Leon** [comment]
Hi, 
thank you for what you pointed out.

You meant  the C++ version SDK API Reference, right?

Just now I edited the thing you said, and you can check it out now.

**Comment by Delet0r** [comment]
Hi Leon,

 

Thats exactly what I ment. I just checked it out, thanks a lot.

 

Have a nice day.

 

Sincerely, Lucas

 

Von: Leon [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Februar 2017 12:26
An: ROBOTIS-GIT/DynamixelSDK <DynamixelSDK@noreply.github.com>
Cc: Delet0r <lucas@humfeldt.de>; Author <author@noreply.github.com>
Betreff: Re: [ROBOTIS-GIT/DynamixelSDK] printRxPacketError (#48)

 

Hi,
thank you for what you pointed out.

You meant the C++ version SDK API Reference, right?

Just now I edited the thing you said, and you can check it out now.

**Comment by ROBOTIS-Leon** [comment]
Ja, Dankeschon und

Ich wunsche auch Ihnen einen schonen Tag
