### ISSUE TITLE
import header for c++

### ISSUE THREAD

**Issue by Delet0r** [ROBOTIS-GIT/DynamixelSDK#49]
Greetings,

I would love to have a import header file to implictly import the dll in to my c++ project.
If there is one and I just have not found, would you be so kind as to tell me where it is.
Thanks in advance.

Sincerely,

Lucas

**Comment by ROBOTIS-Leon** [comment]
Hallo

it is in build-winxx-output-dynamixelsdk.dll folder :)

**Comment by Delet0r** [comment]
Thank you :) 👍
