### ISSUE TITLE
No module named 'dynamixel_sdk'

### ISSUE THREAD

**Issue by Hello970** [ROBOTIS-GIT/DynamixelSDK#504]
ISSUE TEMPLATE ver. 1.2.0

Please fill this template for more accurate and prompt support.

1. Which DYNAMIXEL SDK version do you use?
  `3.7.31`

2. Which programming language/tool do you use?
  `Python`

3. Which operating system do you use?
  `Windows 10`

3. Which USB serial converter do you use?
  `U2D2`

4. Which DYNAMIXEL do you use?
  `MX-64AR(2.0)`

5. Have you searched the issue from the closed issue threads?
Yes, I checked some others met the same problem, but according to the answer given by ROBOTIS-David, the problem still cannot be solved (https://www.gitmemory.com/issue/ROBOTIS-GIT/DynamixelSDK/462/767229757).

6. Please describe the issue in detail
This is my first time using dynamixel with Python, and I cannot seem to get dynamixel sdk set up without producing a "No module named 'dynamixel_sdk'" error when running the protocol 2 test files and my own code. To install dynamixel sdk, I followed the following two robotis videos:

https://www.youtube.com/watch?v=XMCPJFqoH10
https://www.youtube.com/watch?v=pZmueNctY0s

I have repeated the processes in the videos multiple times with identical results. I also tried googling my issue and was unable to find a solution. As shown in attached figures 1 and 2, it seems the dynamixel_sdk has been installed, but when I try to test the code, it gives error " No module named 'dynamixel_sdk' ".
![1](https://user-images.githubusercontent.com/58330756/120573497-a76c7080-c458-11eb-91e1-82da09e17009.png)
![2](https://user-images.githubusercontent.com/58330756/120573511-acc9bb00-c458-11eb-9dc5-71bc65d735ca.png)
![3](https://user-images.githubusercontent.com/58330756/120573523-afc4ab80-c458-11eb-9ddd-01f625c5c362.png)

7. How can we reproduce the issue?
By following the steps I described above. Thanks for your attention.

**Comment by ROBOTIS-Will** [comment]
Hi @Hello970 
Have you tried running the examples in the SDK?
Are you also getting the same error?
If the installed library cannot be found, make sure to add the library path to the path in windows environment.

**Comment by Hello970** [comment]
Hi Sir, I have solved this problem by reinstalling Python. It might be caused by incorrect path. Thanks for your attention!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Will ***@***.***>
发送时间: 2021年6月4日 14:04
收件人: ***@***.***>
抄送: ＳＵＮ ***@***.***>; ***@***.***>
主题: Re: [ROBOTIS-GIT/DynamixelSDK] No module named 'dynamixel_sdk' (#504)


Hi @Hello970<https://github.com/Hello970>
Have you tried running the examples in the SDK?
Are you also getting the same error?
If the installed library cannot be found, make sure to add the library path to the path in windows environment.

―
