### ISSUE TITLE
[C++][STM32] Frame error on first group sync write

### ISSUE THREAD

**Issue by schorr31** [ROBOTIS-GIT/DynamixelSDK#521]
1. Which DYNAMIXEL SDK version do you use?
  - `3.7.40`

2. Which programming language/tool do you use?
  - `C++`

3. Which system do you use?
  - `FreeRTOS on STM32 with half duplex serial`

3. Which DYNAMIXEL do you use?
  - `XL430-W250 `

4. Have you searched the issue from the closed issue threads?
  - `yes`

5. Please describe the issue in detail
  - `The first group sync write after the initialisation produces a frame error in the header. The rest of the message is transmitted correctly. See the attached pictures for the first and the second message.`

![write1](https://user-images.githubusercontent.com/60399495/128685194-c875c55a-9117-4e08-83d3-e7f219024e09.PNG)
![write2](https://user-images.githubusercontent.com/60399495/128685205-319477aa-9c5b-4518-b076-eceba90a5ed3.PNG)

**Comment by ROBOTIS-Will** [comment]
Hi @schorr31 
Thank you for reporting the issue.
I'll check on this and get back to you.
Are you running on ROS2?

**Comment by schorr31** [comment]
No i ported the C++ code to work with a STM32 microcontroller. It utilizes the ST hal library for hardware access. The program uses FreeRTOS, which is a real time operating system for microcontrollers.

**Comment by ROBOTIS-Will** [comment]
@schorr31 
Sorry, but the dev environment isn't what I can test of.
Can you check the content of the txpacket array when the frame error occurs?
Right before the TX transmission, header is inserted as a byte on each field and skipping this is very unlikely.

**Comment by schorr31** [comment]
Hello, the problem was the implementation of the STM32 porthandler. Thanks for your help!
