### ISSUE TITLE
tests only running in CMD and not in pycharm

### ISSUE THREAD

**Issue by barak720** [ROBOTIS-GIT/DynamixelSDK#557]
Hey guys,
I've download DynamixelSDK-3.7.31
and I'm using U2D2, a power hub and XL430-W250-T as my setup.

I"m using python via pycharm on windows.

I've installsed the dynamixel sdk libary like the emanual from dynamixel.

I'm trying to run "read_write", wich works great using cmd

![sdkcmd](https://user-images.githubusercontent.com/102663776/162750317-2d4df7e0-e090-4d54-89ce-fd40434478e8.jpg)

but when i run the code in pycharm

![sdkpy](https://user-images.githubusercontent.com/102663776/162750790-341b5c11-9ed3-42eb-95d7-c70cad60a74b.jpg)

"ModuleNotFoundError: No module named 'dynamixel_sdk'"

I've uninstall and installed pycharm again, used Anaconda, nothing helped.

mybe it's a pycharm setup?

I have coded C using visuall studio. and MATLAB before.
first time in python, pycharm and dynamixel.

**Comment by ROBOTIS-Will** [comment]
Hi @barak720 
I'm not quire familiar with the pycharm, but you might need to install the DYNAMIXEL SDK library.
Have you tried something like below?
https://stackoverflow.com/questions/24197970/pycharm-import-external-library

**Comment by barak720** [comment]
Hey @ROBOTIS-Will 
yes I've installed the SDK libary, connected the engine to DYNAMIXEL WIZARD, found the COM, defined it in the code.

thats the thing, the same code works throu CMD, which means the libary is installed, python is working, must be somthing in the Pycharm...

thanks anyway

**Comment by barak720** [comment]
thanks, it was a problem with the interpitator.
i've downloaded visual studio code and it works.
