### ISSUE TITLE
Control the  position and the  velocity simultaneously

### ISSUE THREAD

**Issue by shelderzhang** [ROBOTIS-GIT/DynamixelSDK#63]
Hi! 
      I want control  two Dynamixel_pro actuators with goal positions and goal velocities simultaneously. Firstly, I use DynamixelSDK  GroupSyncWrite to set the goal positions, then I use DynamixelSDK  GroupSyncWrite to set the goal velocities. It seems that the velocity can be controlled. Just the goal positions is tracked.
      How can   control  two Dynamixel_pro actuators with goal positions and goal velocities simultaneously?

**Comment by ROBOTIS-Leon** [comment]
Hi!

Use GroupBulkWrite!
See related example: bulk_read_write.cpp

**Comment by ROBOTIS-Leon** [comment]
or see indirect_address.cpp if you want to control both goal position and velocity of a single PRO

**Comment by shelderzhang** [comment]
Is GroupBulkWrite can be used as
   [ID:1] turn wheel to 200 + [ID:1] blink LED 1(1) + [ID:1] - set P gain 150 + ...
??

**Comment by ROBOTIS-Leon** [comment]
Nope, it will work when you control different items in different PROs

So I added second choice which uses indirect address.

As you can see related instructions for the indirect address, you can set the addresses of goal position and goal velocity nearby themselves in the indirect addresses (starts from 634) and do GroupSyncWrite 8 bytes (4 bytes for goal position, another 4 bytes for goal velocity)

**Comment by shelderzhang** [comment]
ok, thank you!

**Comment by ROBOTIS-Leon** [comment]
Good luck
