### ISSUE TITLE
[TxRxResult] There is no status packet! problem with RX-24F in ubuntu 14.04

### ISSUE THREAD

**Issue by Angit16** [ROBOTIS-GIT/DynamixelSDK#64]
Hi,

I am using RX-24F. I used 12V 2A regulated supply to run it. I checked with Dynamixel Wizard in windows and it shows all the details of the servo as shown in the wiki video. I attempted to run "read_write" function it in ubuntu as suggested in wiki video link. But it does not run. although it shows that the port is open. But it does not show that " dynamixel has been successfully connected".
I tried to run "ping" also and it shows the model number 3328, but [TxRxResult] There is no status packet! is still showing. 

Please help me to fix the problem.

**Comment by Angit16** [comment]
ok, solved it. I had to change the baud rate.

**Comment by ROBOTIS-Leon** [comment]
Great :)
