### ISSUE TITLE
PID control using Dynamixel RX-24F

### ISSUE THREAD

**Issue by Angit16** [ROBOTIS-GIT/DynamixelSDK#66]
Hi,

I am looking forward to implement a PID control loop by writing it in C. Can I get the control over position and velocity by controlling the servo from PC?

thanks,

**Comment by ROBOTIS-Leon** [comment]
you mean an example code?

**Comment by Angit16** [comment]
yes, that would certainly help me. I would more likely look to learn about the RX-24 system, so that I can use a PID control for position and velocity correction.

**Comment by ROBOTIS-Leon** [comment]
Hi,

Sorry, we don't have any example codes released.

If you are suffering on simultaneous multiple item control, 

just think about changing "LED control" to "Velocity control" in indirect_address.c

**Comment by ROBOTIS-Leon** [comment]
This issue will be closed since there was no actions within 7 days.
You can activate this issue whenever.
