### ISSUE TITLE
When the Dynamixel_pro powered in the negative position, the position sensor error

### ISSUE THREAD

**Issue by shelderzhang** [ROBOTIS-GIT/DynamixelSDK#72]
Please fill out the questionaire to give you the best support service.  

- Which DYNAMIXEL is it?

  [　 -PRO M42-10-S260-R　] 

- Which CONTROLLER is it?

  [　PC via USB2Dynamixel　　] 

- Any PICTURES or VIDEOS?

![image](https://cloud.githubusercontent.com/assets/12554852/24988998/f57ab234-203b-11e7-9fb5-de4f4635a2a5.png)
![image](https://cloud.githubusercontent.com/assets/12554852/24989025/24e292ee-203c-11e7-8b01-0a15a74f7729.png)

when Dynamixel_pro powered in the positive position in 10414 it is ok. then  I move it to negative position -2185 and power off it. After  powered again its position changes to 260817. It seems something wrong with the position sensor

**Comment by ROBOTIS-Leon** [comment]
Hi, again

Please try firmware update on Dynamixel by following described in <kbd> [E-Manual](support.robotis.com/en/)</kbd> - <kbd> Software Help </kbd> - <kbd> Robo Plus </kbd>

and check it again.

If it still doesn't work, send your PRO for repair to [Repair Center](http://en.robotis.com/index/service_04.php?tab=4)

**Comment by shelderzhang** [comment]
oh, no

**Comment by ROBOTIS-Leon** [comment]
@shelderzhang 

let me know any updates are available.

**Comment by shelderzhang** [comment]
I have to send it for repair to Repair Center

**Comment by ROBOTIS-Leon** [comment]
@shelderzhang 

Sorry for the inconvenience,

I already told this issue to the center.
We will bring your Dynamixel to your home asap

**Comment by ROBOTIS-Leon** [comment]
@shelderzhang 

Hi,

I'll close this issue until hardware is fixed.

You can reopen this in anytime
