### ISSUE TITLE
AX12 USB2AX DynamixelSDK error "[txrxresult] there is no status packet" on Raspberry pi 3

### ISSUE THREAD

**Issue by ThomasCaspar** [ROBOTIS-GIT/DynamixelSDK#79]
Hello,
I come to you because I use USB2AX on a raspberry pi 3 to control 7 AX12. From time to time my program sends me the error "[txrxresult] there is no status packet" blocking me all the action of the AX12. 
I tried to change the baud rate without success. This error occurs when sending data.

Can you help me ?

**Comment by ROBOTIS-Leon** [comment]
@ThomasCaspar 

Hi,

I need more details to figure it out.

and I guess I saw in the network that [someone (named as apollokit)](https://github.com/apollokit/DynamixelSDK/network) had forked and was working with porting the USB2AX to DynamixelSDK.

**Comment by ThomasCaspar** [comment]
Hi,


My problem is when I send an instruction to AX12 with write2ByteTxRx, sometimes  I have error "[txrxresult] there is no status packet" and Ax12 no reacts. For solve this problem i send in loop the instruction while i have error,  but it's not good solution.

**Comment by ROBOTIS-Leon** [comment]
@ThomasCaspar 

Hi,

Did you see other branches worked for USB2AX?

**Comment by ROBOTIS-Leon** [comment]
This issue will be closed since there was no actions for a while.
You can reopen this issue to show this issue to the users whenever.
