### ISSUE TITLE
How to run Dynamixel MX-28T servo at different speed in Matlab

### ISSUE THREAD

**Issue by fxs587** [ROBOTIS-GIT/DynamixelSDK#83]
- Which DYNAMIXEL is it?

  [　MX-28T　]  

- Which CONTROLLER is it?

  [USB2Dynamixel] 

- Which VERSION of DynamixelSDK is it?

  [DynamixelSDK 3.4.4] 

Hi everybody, I am able to run my dynamixel mx-28t servo motor using Matlab simple read-write example inside SDK file. My question is that in my project, I will need to use 2 servo motor and I have to be able to change their speed and rotation separately in Matlab. I don't know how to change the speed for each motor. Also, when I connect 2 servo motor together, they operate simultaneously which I wanna operate them separately in Matlab. I am wondering does anyone help me?
Thanks a lot in advance.

**Comment by ROBOTIS-Leon** [comment]
@fxs587 

Hi,

I understood what you told as you want to change goal position and goal velocity at the same time with MX?

**Comment by fxs587** [comment]
Hi Leon
 I wanna change the goal position and goal velocity at different times for each servo  MX.  I connected two servos with the same USB dynamixel. I am just able to change the goal rotation and they rotate simultaneously which I don't want. Because I wanna have control to operate the servos with different goal position and velocity at different times.

**Comment by ROBOTIS-Leon** [comment]
@fxs587 

Hi, 

then you should use `read_write` example.

just copy and paste readNbyteTxRx and writeNByteTxRx functions couple of times so that it is able to move multiple motors.

**Comment by fxs587** [comment]
Hi Leon
Thank you so much. How about changing speed? How can I change the speed of each motor?

**Comment by ROBOTIS-Leon** [comment]
@fxs587

Hi again,

the `read_write` example shows changing its `goal position` value, and you may find something starts with `ADDR_` which means the value of the `Control table address` of the Dynamixel you are using with.
So if you change it into other values like the address of `Goal velocity`, which can be referred to [ROBOTIS E-Manual](http://support.robotis.com/) - <kbd>Product Information</kbd> - <kbd>Actuator</kbd> - <kbd>Dynamixel</kbd> - <kbd>MX Series</kbd> - <kbd>MX-28AT</kbd> - Control Table Moving Speed, it will move as you want.

**Comment by GrigoriyAY** [comment]
Hi fxs587,

I used with command for dynamixel library:
calllib('dynamixel', 'dxl_write_word',ID,32,SpeedValue)

**Comment by ROBOTIS-Leon** [comment]
This issue will be closed since there was no actions for a while.
You can reopen this issue to show this issue to the users whenever.
